// Generated by uniffi-bindgen-react-native (Nitro backend)
//
// Tells the React Native CLI autolinker where this package lives on each
// platform. The `packageInstance` we register on Android is NOT a
// TurboModule — it's a thin `BaseReactPackage` whose `companion object`
// runs `System.loadLibrary("{{ self.config.project.module_cpp() }}")` the
// first time RN instantiates the package. That dlopen triggers
// `JNI_OnLoad` in `android/cpp-adapter.cpp`, which calls
// `margelo::nitro::{{ self.config.project.cpp_namespace() }}::registerAllNatives()`,
// which finally registers the HybridObject constructor with Nitro's
// `HybridObjectRegistry`. Without this chain,
// `NitroModules.createHybridObject(…)` throws at runtime.
//
// iOS doesn't need the equivalent dance — `+ (void) load` runs the
// `NitroTestAutolinking.mm` block automatically.
const path = require('path');

module.exports = {
    dependency: {
        platforms: {
            android: {
                sourceDir: './android',
                packageImportPath: 'import com.margelo.nitro.{{ self.config.project.cpp_namespace() }}.{{ self.config.project.module_cpp() }}Package;',
                packageInstance: 'new {{ self.config.project.module_cpp() }}Package()',
            },
            ios: {
                podspecPath: path.join(__dirname, '{{ self.config.project.podspec_filename() }}.podspec'),
            },
        },
    },
};
