// Generated by uniffi-bindgen-react-native (Nitro backend)
//
// React Native autolinking instantiates this class as part of the host
// app's package list. The `companion object { init { … } }` block fires
// the first time the class is loaded, which triggers
// `{{ self.config.project.module_cpp() }}OnLoad.initializeNative()` →
// `System.loadLibrary("{{ self.config.project.module_cpp() }}")` →
// `JNI_OnLoad` in `cpp-adapter.cpp` →
// `margelo::nitro::{{ self.config.project.cpp_namespace() }}::registerAllNatives()` →
// `HybridObjectRegistry::registerHybridObjectConstructor("{{ self.config.project.spec_name() }}Installer", …)`.
// That chain is what makes `NitroModules.createHybridObject<{{ self.config.project.spec_name() }}Installer>(…)`
// resolve at runtime.
//
// Pattern matches `react-native-nitro-test`'s `NitroTestPackage`. We don't
// expose any TurboModules or ViewManagers — the HybridObject lives in
// Nitro's own registry, not React Native's.
package com.margelo.nitro.{{ self.config.project.cpp_namespace() }}

import com.facebook.react.BaseReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.model.ReactModuleInfoProvider
import com.facebook.react.uimanager.ViewManager

class {{ self.config.project.module_cpp() }}Package : BaseReactPackage() {
  override fun getModule(
    name: String,
    reactContext: ReactApplicationContext,
  ): NativeModule? = null

  override fun getReactModuleInfoProvider(): ReactModuleInfoProvider =
    ReactModuleInfoProvider { HashMap() }

  override fun createViewManagers(
    reactContext: ReactApplicationContext,
  ): List<ViewManager<*, *>> = emptyList()

  companion object {
    init {
      {{ self.config.project.module_cpp() }}OnLoad.initializeNative()
    }
  }
}
