// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
//
// Nitro doesn't use the JSI installer pattern: each HybridObject is
// registered by Nitrogen's autolinking, so `createHybridObject<Spec>(name)`
// inside the per-namespace `<namespace>.ts` modules below is enough.
//
// This file aggregates every gen_nitro-emitted namespace into the single
// entrypoint that `package.json#main` points at, so consumers can write
// `import { foo } from 'react-native-<project>'` and reach any namespace
// API without knowing about the layout under `src/bindings/`.

{%- let root = self.project_root() %}
{%- let bindings = self.config.project.bindings.ts_path(root) %}
{%- let bindings = self.relative_to(root, bindings) %}

// Re-export every emitted namespace module flat: the `<Namespace>Api` /
// HybridObject types from the `.nitro.ts` spec, the record / enum DTOs, the
// per-interface runtime classes, the error helpers, and the singleton
// accessor function.
//
// Flat (`export *`) matches all three sibling backends (JSI / WASM / -node),
// so a consumer can `import { foo } from 'react-native-<project>'` without a
// `<ns>.` prefix (audit bug #19). Cross-namespace DTO collisions, when they
// occur (multiple modules declaring same-named records), are solved narrowly
// at those modules rather than by blanket-namespacing every single-module
// project.
{%- for m in self.config.modules %}
export * from './{{ bindings }}/{{ m.ts() }}';
{%- endfor %}

// Parity with the index.web.ts variant. The native flow is sync; this is a
// no-op so consumer code can `await` regardless of platform.
export async function uniffiInitAsync() {
  // NOOP.
}

