# Generated by uniffi-bindgen-react-native (Nitro backend)
require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name         = "{{ self.config.project.podspec_filename() }}"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = package["homepage"]
  s.license      = package["license"]
  s.authors      = package["author"]

  s.platforms    = { :ios => min_ios_version_supported }
  s.source       = { :git => "{{ self.config.project.repository() }}", :tag => "#{s.version}" }
{%- let root = self.project_root() %}
{%- let dir = self.config.project.ios.framework_path(root) %}
{%- let framework = self.relative_to(root, dir) %}
{%- let dir = self.config.project.tm.cpp_path(root) %}
{%- let tm = self.relative_to(root, dir) %}
{%- let dir = self.config.project.bindings.cpp_path(root) %}
{%- let bindings = self.relative_to(root, dir) %}

  # ubrn-emitted C++ sources: the uniffi FFI glue ({{ tm }}), every Nitro
  # HybridObject impl, and register_natives.cpp ({{ bindings }}). The static
  # initializer in register_natives.cpp registers every HybridObject with the
  # HybridObjectRegistry at library-load time, so there is no nitrogen-
  # generated autolinking ruby to load and no nitrogen file helper to call.
  s.source_files = "{{ tm }}/**/*.{hpp,cpp,c,h}", "{{ bindings }}/**/*.{hpp,cpp,c,h}"
  s.vendored_frameworks = "{{ framework }}"
  s.dependency    "uniffi-bindgen-react-native", "{{ self.config.project.ubrn_version() }}"

  # The Nitro Modules runtime pod: HybridObject + Dispatcher +
  # HybridObjectRegistry (and libc++_shared). This is the only Nitro
  # dependency we keep.
  s.dependency "NitroModules"

  # C++20 + Swift/Obj-C++ interop settings the Nitro runtime needs. nitrogen's
  # file helper set these; we set them inline since we no longer call it.
  current_pod_target_xcconfig = s.attributes_hash["pod_target_xcconfig"] || {}
  s.pod_target_xcconfig = current_pod_target_xcconfig.merge({
    "CLANG_CXX_LANGUAGE_STANDARD" => "c++20",
    "SWIFT_OBJC_INTEROP_MODE" => "objcxx",
    "DEFINES_MODULE" => "YES",
    "SWIFT_INSTALL_OBJC_HEADER" => "NO",
  })

  # Use install_modules_dependencies helper if React Native >=0.71.0.
  if respond_to?(:install_modules_dependencies, true)
    install_modules_dependencies(s)
  else
    s.dependency "React-Core"
  end
end
