# Generated by uniffi-bindgen-react-native (Nitro backend)
require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name         = "{{ self.config.project.podspec_filename() }}"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = package["homepage"]
  s.license      = package["license"]
  s.authors      = package["author"]

  s.platforms    = { :ios => min_ios_version_supported }
  s.source       = { :git => "{{ self.config.project.repository() }}", :tag => "#{s.version}" }
{%- let root = self.project_root() %}
{%- let dir = self.config.project.ios.framework_path(root) %}
{%- let framework = self.relative_to(root, dir) %}
{%- let dir = self.config.project.tm.cpp_path(root) %}
{%- let tm = self.relative_to(root, dir) %}
{%- let dir = self.config.project.bindings.cpp_path(root) %}
{%- let bindings = self.relative_to(root, dir) %}

  # ubrn-emitted C++ sources (uniffi FFI glue + the Nitro HybridObject installer).
  s.source_files = "{{ tm }}/**/*.{hpp,cpp,c,h}", "{{ bindings }}/**/*.{hpp,cpp,c,h}"
  s.vendored_frameworks = "{{ framework }}"
  s.dependency    "uniffi-bindgen-react-native", "{{ self.config.project.ubrn_version() }}"

  # Pull in Nitrogen's generated specs + Swift/C++ bridges + Nitro autolinking.
  load File.join(__dir__, "nitrogen/generated/ios/{{ self.config.project.module_cpp() }}+autolinking.rb")
  add_nitrogen_files(s)

  # Use install_modules_dependencies helper if React Native >=0.71.0.
  if respond_to?(:install_modules_dependencies, true)
    install_modules_dependencies(s)
  else
    s.dependency "React-Core"
  end
end
