// Generated by uniffi-bindgen-react-native (Nitro backend)
//
// `JNI_OnLoad` is the C++ entrypoint Android calls the *first* time
// `System.loadLibrary("{{ self.config.project.module_cpp() }}")` runs.
// Nitrogen requires us to invoke `registerAllNatives()` here — it's where
// every Hybrid Object's JNI bridge gets registered with `fbjni` and where
// `HybridObjectRegistry::registerHybridObjectConstructor("{{ self.config.project.spec_name() }}Installer", …)`
// is finally called.
//
// The kotlin `{{ self.config.project.module_cpp() }}Package` class loads this
// .so from its `companion object { init { … } }` block (see
// `android/src/main/java/com/margelo/nitro/{{ self.config.project.cpp_namespace() }}/{{ self.config.project.module_cpp() }}Package.kt`).
// React Native picks the package up via `packageInstance` in
// `react-native.config.js`.

#include <fbjni/fbjni.h>
#include <jni.h>

#include "{{ self.config.project.module_cpp() }}OnLoad.hpp"

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void*) {
  return facebook::jni::initialize(vm, []() {
    margelo::nitro::{{ self.config.project.cpp_namespace() }}::registerAllNatives();
  });
}
