// Generated by uniffi-bindgen-react-native (Nitro backend)
//
// `JNI_OnLoad` is the C++ entrypoint Android calls the *first* time
// `System.loadLibrary("{{ self.config.project.module_cpp() }}")` runs.
//
// We do NOT register HybridObjects here: that happens automatically at
// library-load time via the static initializer in `register_natives.cpp`
// (which runs the moment this .so is mapped in, before any JS executes).
// `JNI_OnLoad` only needs to initialize fbjni and return `JNI_VERSION_1_6`
// so that `System.loadLibrary` succeeds. No nitrogen OnLoad is involved.
//
// The kotlin `{{ self.config.project.module_cpp() }}Package` class loads this
// .so from its `companion object { init { … } }` block (see
// `android/src/main/java/com/margelo/nitro/{{ self.config.project.cpp_namespace() }}/{{ self.config.project.module_cpp() }}Package.kt`).
// React Native picks the package up via `packageInstance` in
// `react-native.config.js`.

#include <fbjni/fbjni.h>
#include <jni.h>

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void*) {
  return facebook::jni::initialize(vm, []() {
    // HybridObjects were already registered by the static initializer in
    // register_natives.cpp when this .so was loaded. Nothing to do here.
  });
}
