// Generated by uniffi-bindgen-react-native (Nitro backend)
//
// React Native autolinking instantiates this class as part of the host
// app's package list. The `companion object { init { … } }` block fires
// the first time the class is loaded; it calls
// `System.loadLibrary("{{ self.config.project.module_cpp() }}")`, which maps
// the C++ shared library in. That triggers two things automatically:
//   * `JNI_OnLoad` in `cpp-adapter.cpp` (initializes fbjni), and
//   * the static initializer in `register_natives.cpp`, which populates
//     `HybridObjectRegistry` with every HybridObject constructor.
// That is what makes `NitroModules.createHybridObject<T>(…)` resolve at
// runtime — no nitrogen OnLoad codegen is involved.
//
// Pattern matches `react-native-nitro-test`'s `NitroTestPackage`. We don't
// expose any TurboModules or ViewManagers — the HybridObjects live in
// Nitro's own registry, not React Native's.
package com.margelo.nitro.{{ self.config.project.cpp_namespace() }}

import android.util.Log
import com.facebook.react.BaseReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.model.ReactModuleInfoProvider
import com.facebook.react.uimanager.ViewManager

class {{ self.config.project.module_cpp() }}Package : BaseReactPackage() {
  override fun getModule(
    name: String,
    reactContext: ReactApplicationContext,
  ): NativeModule? = null

  override fun getReactModuleInfoProvider(): ReactModuleInfoProvider =
    ReactModuleInfoProvider { HashMap() }

  override fun createViewManagers(
    reactContext: ReactApplicationContext,
  ): List<ViewManager<*, *>> = emptyList()

  companion object {
    private const val TAG = "{{ self.config.project.module_cpp() }}Package"

    init {
      try {
        Log.i(TAG, "Loading {{ self.config.project.module_cpp() }} C++ library...")
        System.loadLibrary("{{ self.config.project.module_cpp() }}")
        Log.i(TAG, "Successfully loaded {{ self.config.project.module_cpp() }} C++ library!")
      } catch (e: Error) {
        Log.e(
          TAG,
          "Failed to load {{ self.config.project.module_cpp() }} C++ library! Is it properly installed and linked? " +
            "Is the name correct? (see `CMakeLists.txt`, at `add_library(...)`)",
          e,
        )
        throw e
      }
    }
  }
}
