// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
//
// Nitro doesn't use the JSI installer pattern: each HybridObject is
// registered by Nitrogen's autolinking, so `createHybridObject<Spec>(name)`
// inside the per-namespace `<namespace>.ts` modules below is enough.
//
// This file aggregates every gen_nitro-emitted namespace into the single
// entrypoint that `package.json#main` points at, so consumers can write
// `import { foo } from 'react-native-<project>'` and reach any namespace
// API without knowing about the layout under `src/bindings/`.

{%- let root = self.project_root() %}
{%- let bindings = self.config.project.bindings.ts_path(root) %}
{%- let bindings = self.relative_to(root, bindings) %}

// Re-export every emitted namespace module: the `<Namespace>Api` /
// HybridObject types from the `.nitro.ts` spec plus the singleton
// accessor function.
{%- for m in self.config.modules %}
export * from './{{ bindings }}/{{ m.ts() }}';
{%- endfor %}

// Parity with the index.web.ts variant. The native flow is sync; this is a
// no-op so consumer code can `await` regardless of platform.
export async function uniffiInitAsync() {
  // NOOP.
}
