# Generated by uniffi-bindgen-react-native (Nitro backend)
require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name         = "{{ self.config.project.podspec_filename() }}"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = package["homepage"]
  s.license      = package["license"]
  s.authors      = package["author"]

  s.platforms    = { :ios => min_ios_version_supported }
  s.source       = { :git => "{{ self.config.project.repository() }}", :tag => "#{s.version}" }
{%- let root = self.project_root() %}
{%- let dir = self.config.project.ios.framework_path(root) %}
{%- let framework = self.relative_to(root, dir) %}
{%- let dir = self.config.project.tm.cpp_path(root) %}
{%- let tm = self.relative_to(root, dir) %}
{%- let dir = self.config.project.bindings.cpp_path(root) %}
{%- let bindings = self.relative_to(root, dir) %}

  # ubrn-emitted C++ sources. iOS compiles K unity/amalgamation chunks under
  # {{ bindings }}/amalgam/ (each #include-ing a disjoint subset of the
  # per-object Hybrid*.cpp) PLUS register_natives.cpp — NOT the per-object
  # .cpp themselves. This collapses ~one-TU-per-object down to ~K TUs so the
  # shared-header DWARF stops overflowing libtool's 32-bit Mach-O .a member
  # offset (>4GB). All headers are still copied so the chunks' nested
  # includes resolve. The static initializer in register_natives.cpp
  # registers every HybridObject with the HybridObjectRegistry at library-
  # load time, so there is no nitrogen autolinking ruby to load.
  s.source_files = "{{ tm }}/**/*.{hpp,h}", "{{ bindings }}/**/*.{hpp,h}", "{{ bindings }}/amalgam/*.cpp", "{{ bindings }}/register_natives.cpp"
  s.vendored_frameworks = "{{ framework }}"
  s.dependency    "uniffi-bindgen-react-native", "{{ self.config.project.ubrn_version() }}"

  # The Nitro Modules runtime pod: HybridObject + Dispatcher +
  # HybridObjectRegistry (and libc++_shared). This is the only Nitro
  # dependency we keep.
  s.dependency "NitroModules"

  # C++20 + Swift/Obj-C++ interop settings the Nitro runtime needs. nitrogen's
  # file helper set these; we set them inline since we no longer call it.
  current_pod_target_xcconfig = s.attributes_hash["pod_target_xcconfig"] || {}
  current_header_search_paths = Array(current_pod_target_xcconfig["HEADER_SEARCH_PATHS"])
  s.pod_target_xcconfig = current_pod_target_xcconfig.merge({
    "CLANG_CXX_LANGUAGE_STANDARD" => "c++20",
    "SWIFT_OBJC_INTEROP_MODE" => "objcxx",
    "DEFINES_MODULE" => "YES",
    "SWIFT_INSTALL_OBJC_HEADER" => "NO",
    # The generated C++ angle-includes the ubrn runtime headers WITHOUT a
    # pod-name prefix (<RustBuffer.h>, <NitroUniffi.hpp>, <nitro-uniffi/...>),
    # which live in the separate `uniffi-bindgen-react-native` pod. CocoaPods
    # copies that pod's headers under Pods/Headers/Public/<podname>/ preserving
    # the nitro-uniffi/ subdir (the runtime podspec sets header_mappings_dir),
    # so put that directory on the search path for the bare/subdir includes to
    # resolve. `$(inherited)` keeps the NitroModules / React paths that
    # install_modules_dependencies injects.
    "HEADER_SEARCH_PATHS" => (current_header_search_paths + [
      "$(inherited)",
      "\"$(PODS_TARGET_SRCROOT)/{{ bindings }}\"",
      "\"$(PODS_ROOT)/Headers/Public/uniffi-bindgen-react-native\"",
    ]).join(" "),
  })

  # Use install_modules_dependencies helper if React Native >=0.71.0.
  if respond_to?(:install_modules_dependencies, true)
    install_modules_dependencies(s)
  else
    s.dependency "React-Core"
  end
end
