/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/
 */

use anyhow::Result;
use clap::{Args, Subcommand};
use ubrn_bindgen::{ModuleMetadata, OutputArgs, SourceArgs, SwitchArgs};

use crate::{
    codegen::{get_template_config, render_files},
    commands::ConfigArgs,
    jsi, ProjectConfig,
};

#[derive(Args, Debug)]
pub(crate) struct CmdArg {
    #[clap(subcommand)]
    cmd: Cmd,
}
impl CmdArg {
    pub(crate) fn run(&self) -> Result<()> {
        self.cmd.run()
    }
}

#[derive(Debug, Subcommand)]
enum Cmd {
    /// Generate the TurboModule code to plug the bindings into the app
    TurboModule(TurboModuleArgs),
    /// Generate Nitro Module glue (HybridObject installer + nitro.json) so
    /// the bindings can be plugged into the app via Nitro Modules autolinking
    /// instead of the React Native TurboModule registry.
    Nitro(NitroArgs),
    /// Generate just the Typescript and C++ bindings
    Bindings(BindingsArgs),
}

impl Cmd {
    fn run(&self) -> Result<()> {
        match self {
            Self::Bindings(b) => {
                let b = ubrn_bindgen::BindingsArgs::from(b);
                b.run(None)?;
                Ok(())
            }
            Self::TurboModule(t) => {
                t.run()?;
                Ok(())
            }
            Self::Nitro(n) => {
                n.run()?;
                Ok(())
            }
        }
    }
}

#[derive(Args, Debug)]
pub(crate) struct BindingsArgs {
    #[command(flatten)]
    pub(crate) source: SourceArgs,
    #[command(flatten)]
    pub(crate) output: OutputArgs,
}

impl From<&BindingsArgs> for ubrn_bindgen::BindingsArgs {
    fn from(value: &BindingsArgs) -> Self {
        ubrn_bindgen::BindingsArgs::new(
            SwitchArgs::default(),
            value.source.clone(),
            value.output.clone(),
        )
    }
}

#[derive(Args, Debug)]
pub(crate) struct TurboModuleArgs {
    #[clap(flatten)]
    config: ConfigArgs,

    /// The namespaces that are generated by `generate jsi bindings`.
    namespaces: Vec<String>,

    /// Whether to generate native bindings or not.
    #[clap(long, default_value = "false")]
    native_bindings: bool,
}

impl TurboModuleArgs {
    pub(crate) fn run(&self) -> Result<()> {
        let project = ProjectConfig::try_from(self.config.clone())?;
        let modules = self
            .namespaces
            .iter()
            .map(|s| ModuleMetadata::new(s))
            .collect();
        let rust_crate = project.crate_.metadata()?;
        // The TurboModule subcommand bypasses the bindings phase
        // entirely, so there's no `gen_nitro` output and the
        // `nitro_hybrid_objects` slot is empty.
        let config = get_template_config(
            project,
            rust_crate,
            modules,
            Vec::new(),
            self.native_bindings,
        );
        let files = jsi::get_files(config.clone());
        render_files(config.clone(), files.into_iter())?;
        Ok(())
    }
}

#[derive(Args, Debug)]
pub(crate) struct NitroArgs {
    #[clap(flatten)]
    config: ConfigArgs,

    /// The namespaces that are generated by `generate jsi bindings`.
    namespaces: Vec<String>,

    /// Whether to generate native bindings or not.
    #[clap(long, default_value = "false")]
    native_bindings: bool,
}

impl NitroArgs {
    pub(crate) fn run(&self) -> Result<()> {
        let project = ProjectConfig::try_from(self.config.clone())?;
        let modules = self
            .namespaces
            .iter()
            .map(|s| ModuleMetadata::new(s))
            .collect();
        let rust_crate = project.crate_.metadata()?;
        // This is the `generate jsi nitro` subcommand path — it emits
        // platform glue without re-running `gen_nitro`. The hybrid object
        // list isn't available here; the templates fall back to an empty
        // autolinking block / source list, which is correct for the
        // "templates-only" callable invariant.
        let config = get_template_config(
            project.clone(),
            rust_crate,
            modules,
            Vec::new(),
            self.native_bindings,
        );

        // Emit the full Nitro file set: cross-platform installer + nitro.json
        // *and* the per-platform build wiring (gradle/cmake for Android,
        // podspec for iOS). The codegen layer rewrites by path so the
        // cross-platform pieces shared by both sets render once.
        let mut files = jsi::nitro::get_files_for_android(config.clone());
        files.extend(jsi::nitro::get_files_for_ios(config.clone()));
        render_files(config.clone(), files.into_iter())?;

        // We never invoke nitrogen: the emitted gradle/cmake/podspec are
        // self-contained and compile our own C++ sources. HybridObject
        // registration happens at library-load time via the static
        // initializer in `register_natives.cpp`.
        Ok(())
    }
}
