// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// iOS unity/amalgamation chunk. CocoaPods compiles these K chunks instead
// of the per-object Hybrid*.cpp so the shared-header DWARF is emitted ~K
// times instead of once per object, keeping libtool's classic Mach-O .a
// member offsets under the 32-bit (4GB) limit. Android does NOT compile
// these — its CMakeLists enumerates the per-object .cpp directly.
//
// Each #include pastes one per-object translation unit; its own nested
// quote-includes ("HybridFoo.hpp", "<ns>_codecs.hpp") resolve relative to
// cpp/generated/ (the directory of the file physically containing the
// directive), so no extra search path is required for the paste to build.
{%- for cxx_class in includes %}
#include "../{{ cxx_class }}.cpp"
{%- endfor %}
