// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
//
// iOS autolinking translation unit (Objective-C++). This is the canonical
// Nitrogen registration mechanism: an Objective-C class with a `+ (void)load`
// method that registers every emitted HybridObject with Nitro's process-global
// `HybridObjectRegistry` the moment the Objective-C runtime loads the class.
//
// Why this file exists ALONGSIDE `register_natives.cpp` (audit bug #5):
// CocoaPods links the ubrn pod as a STATIC archive (`.a`). The C++
// `register_natives.cpp` registers via a file-scope static initializer
// (`RegisterOnLoad register_on_load;`) whose only external symbol is
// `extern "C" void registerNatives` — which the generated app entrypoint never
// references (it uses `NitroModules.createHybridObject<T>()` only). ld64 drops
// an archive member whose sole external symbol is unreferenced, so on a real
// device that static initializer never runs and the registry is EMPTY: every
// `createHybridObject` throws. The desktop Hermes test runner masks this by
// `dlsym`-calling `registerNatives` after `dlopen`, so the gate never sees it.
//
// An Objective-C class's `+load` is different: the app is built with `-ObjC`
// (the React Native / Expo default), which force-loads every archive member
// that defines an Objective-C class or category, and the Objective-C runtime
// invokes `+load` on every loaded class at image-load time — before `main()`,
// before any JS. So this TU's registration runs on device exactly when the
// `register_natives.cpp` static initializer was being stripped.
//
// Coexistence: registration funnels through the SAME process-global
// `HybridObjectRegistry`. Re-registering the same name is the registry's own
// concern; in practice on iOS only `+load` runs (the app never references
// `registerNatives`), and on desktop only `registerNatives` runs (this `.mm`
// is not compiled there). Both call sites are idempotent w.r.t. the app's
// intent — the registry holds one constructor per name.
//
// Android is unaffected: this is an Objective-C++ `.mm`, and the Android
// CMakeLists enumerates only `.cpp` (per-object impls + `register_natives.cpp`
// + `cpp-adapter.cpp`), never `.mm`. The Android `.so` registers via the
// `register_natives.cpp` static initializer at `System.loadLibrary` / dlopen.

#import <Foundation/Foundation.h>

#include <NitroModules/HybridObjectRegistry.hpp>
#include <memory>

{%- for entry in hybrid_objects %}
// Pull the impl in so the constructor symbol is available at link time.
#include "{{ entry.cxx_class }}.hpp"
{%- endfor %}

@interface UbrnNitroAutolinking : NSObject
@end

@implementation UbrnNitroAutolinking

+ (void)load {
  using namespace margelo::nitro;
{%- for entry in hybrid_objects %}
  // Guard each registration: `registerHybridObjectConstructor` THROWS on a
  // duplicate name. On desktop only `register_natives.cpp` registers (this TU
  // isn't compiled there); on iOS only this `+load` does (register_natives.cpp's
  // static initializer is dead-stripped). But should both ever reach the same
  // process-global registry, the `hasHybridObject` check makes the loser a
  // safe no-op instead of a load-time crash.
  if (!HybridObjectRegistry::hasHybridObject("{{ entry.name }}")) {
    HybridObjectRegistry::registerHybridObjectConstructor(
        "{{ entry.name }}",
        []() -> std::shared_ptr<HybridObject> {
          return std::make_shared<::margelo::nitro::{{ entry.cxx_namespace }}::{{ entry.cxx_class }}>();
        });
  }
{%- endfor %}
}

@end
