// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// C++ trampoline impl for uniffi callback interface `{{ cb.ts_name }}`
// in crate `{{ module.crate_name }}`.
//
// Wiring overview:
//
//   1. JS code creates a `{{ cb.cxx_class }}` subclass and hands it
//      to a method that takes a `{{ cb.ts_name }}` parameter.
//   2. The generated method body calls
//      `CallbackHandleMap<{{ cb.cxx_class }}>::instance().insert(...)`
//      which yields a `uint64_t` handle.
//   3. The handle is passed across the C ABI to Rust.
//   4. Rust dispatches into our vtable trampolines below (one per
//      callback method) using that handle.
//   5. Each trampoline looks up the shared_ptr by handle, lifts the
//      Rust-side args into C++ types, invokes the HybridObject method,
//      and lowers the return back to the C-ABI form.
//   6. When Rust drops its last reference, it calls `free_trampoline`,
//      which removes the entry from the handle map.
//
// The actual `FfiStruct` shape for the vtable (one function pointer
// per method, in declared order, followed by clone + free) is
// generated by uniffi; we don't have its field layout in our IR walk.
// `ensure_{{ cb.ts_name }}_vtable_init` is the hook where a
// downstream emission pass will materialize that struct and call
// `{{ cb.vtable_init_symbol }}` with a pointer to it. Until then we
// surface a one-time runtime warning so the test harness can observe
// the codepath being reached.

#include "{{ cb.cxx_class }}.hpp"

#include <atomic>
#include <cstdio>
#include <stdexcept>

extern "C" {
/// Rust-side hook: foreign code installs a vtable by calling this with
/// a pointer to its per-callback FfiStruct. The struct shape is
/// `(*method_1, *method_2, ..., *clone, *free)` in the order the
/// uniffi metadata lists them.
///
/// The pointer type is opaque here — the generated vtable struct is
/// per-callback so we type-erase to `void*` at this boundary; the
/// callsite that actually allocates the struct (in the
/// `ensure_*_vtable_init` body, to be filled in by a follow-up pass)
/// casts back to the project-specific FfiStruct type.
void {{ cb.vtable_init_symbol }}(void* vtable_ptr);
}

namespace margelo::nitro::{{ module.namespace }} {

void {{ cb.cxx_class }}::loadHybridMethods() {
  HybridObject::loadHybridMethods();
  registerHybrids(this, [](Prototype& prototype) {
{%- for method in cb.methods %}
    prototype.registerHybridMethod("{{ method.ts_name }}", &{{ cb.cxx_class }}::{{ method.cxx_name }});
{%- endfor %}
  });
}

{% for method in cb.methods %}
{{ method.return_kind.cxx_type() }} {{ cb.cxx_class }}::{{ method.cxx_name }}(
{%- for arg in method.args -%}
    {{ arg.ty.cxx_type() }} /* {{ arg.ts_name }} */{% if !loop.last %}, {% endif %}
{%- endfor -%}
) {
  throw std::runtime_error(
      "{{ cb.ts_name }}::{{ method.cxx_name }} not implemented — "
      "this method must be overridden by a JS-side HybridObject subclass");
}
{% endfor %}

namespace {

using HandleMap = ubrn::nitro::CallbackHandleMap<{{ cb.cxx_class }}>;

/// Per-method trampolines. Each is a function pointer that Rust calls
/// with the handle + the lowered argument list. We lift each arg using
/// the matching codec, invoke the HybridObject method, and lower the
/// return.
//
// Signatures here follow uniffi's vtable wire format: the first arg
// is always the handle; primitives pass by value; everything else is
// a `RustBuffer`. The trailing `UniffiRustCallStatus*` lets us report
// JS-side exceptions back to Rust.

{% for method in cb.methods %}
extern "C" {{ method.return_kind.c_type() }} {{ cb.ts_name }}_trampoline_{{ method.cxx_name }}(
    uint64_t self_handle
{%- for arg in method.args %},
    {{ arg.ty.c_type() }} {{ arg.ts_name }}_lowered
{%- endfor -%},
    UniffiRustCallStatus* status
) {
    try {
        auto self = HandleMap::instance().get(self_handle);
{%- for arg in method.args %}
        auto {{ arg.ts_name }} = {{ arg.lifted_from_lowered_expr() }};
{%- endfor %}
{%- match method.return_kind %}
{%- when crate::bindings::gen_nitro::model::ReturnKind::Void %}
        self->{{ method.cxx_name }}(
{%- for arg in method.args -%}
            {{ arg.ts_name }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
        );
        status->code = 0;
{%- when crate::bindings::gen_nitro::model::ReturnKind::Value with (ret_ty) %}
        auto __out = self->{{ method.cxx_name }}(
{%- for arg in method.args -%}
            {{ arg.ts_name }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
        );
        status->code = 0;
        return {{ ret_ty.lower_expr("__out", module.rustbuffer_alloc, module.rustbuffer_reserve) }};
{%- endmatch %}
    } catch (const std::exception& e) {
        // Surface JS-side exceptions back to Rust as unexpected errors
        // (code=2). A follow-up pass can route typed uniffi errors via
        // a per-error encoder.
        status->code = 2;
        status->error_buf = RustBuffer{};
        (void)e;
{%- match method.return_kind %}
{%- when crate::bindings::gen_nitro::model::ReturnKind::Void %}
{%- when crate::bindings::gen_nitro::model::ReturnKind::Value with (_) %}
        return {};
{%- endmatch %}
    }
{%- match method.return_kind %}
{%- when crate::bindings::gen_nitro::model::ReturnKind::Void %}
{%- when crate::bindings::gen_nitro::model::ReturnKind::Value with (_) %}
    // Unreachable — every branch above returns or throws.
    return {};
{%- endmatch %}
}
{% endfor %}

/// Clone trampoline. Rust calls this when it wants a second reference
/// to the same foreign-side instance. The `CallbackHandleMap` already
/// stores a `shared_ptr`, so we just look it up and re-insert.
extern "C" uint64_t {{ cb.ts_name }}_trampoline_clone(uint64_t handle, UniffiRustCallStatus* status) {
    try {
        auto self = HandleMap::instance().get(handle);
        status->code = 0;
        return HandleMap::instance().insert(self);
    } catch (...) {
        status->code = 2;
        status->error_buf = RustBuffer{};
        return 0;
    }
}

/// Free trampoline. Rust calls this once per *insert*. Dropping the
/// map entry releases the held shared_ptr; if no other holder remains
/// (i.e. JS already let go), the HybridObject's destructor runs here.
extern "C" void {{ cb.ts_name }}_trampoline_free(uint64_t handle, UniffiRustCallStatus* status) {
    HandleMap::instance().remove(handle);
    status->code = 0;
}

} // namespace

void ensure_{{ cb.ts_name }}_vtable_init() {
    // Idempotent guard — the vtable install happens at most once per
    // process lifetime. We use the relaxed compare/exchange pattern
    // because the vtable install is itself thread-safe on the Rust
    // side (the init fn writes into a `OnceLock`-like slot).
    static std::atomic<bool> installed{false};
    bool expected = false;
    if (!installed.compare_exchange_strong(expected, true)) {
        return;
    }

    // NOTE: the actual vtable struct shape (which is what
    // `{{ cb.vtable_init_symbol }}` consumes) is a uniffi FfiStruct of
    // function pointers we don't yet materialize in this codegen
    // pass — emitting the struct requires walking the
    // `general::Namespace::ffi_definitions` and finding the struct by
    // name. The trampoline functions above are ready to be slotted in;
    // a follow-up pass will allocate the struct and call:
    //
    //     static VTable_for_{{ cb.vtable_init_symbol }} vtable = {
{%- for method in cb.methods %}
    //         /* method_{{ loop.index }} */ &{{ cb.ts_name }}_trampoline_{{ method.cxx_name }},
{%- endfor %}
    //         /* clone */ &{{ cb.ts_name }}_trampoline_clone,
    //         /* free  */ &{{ cb.ts_name }}_trampoline_free,
    //     };
    //     {{ cb.vtable_init_symbol }}(&vtable);
    //
    // Until then, log once so the test harness can see we got here.
    std::fprintf(stderr,
        "[ubrn-nitro] callback vtable init stub reached for "
        "`{{ cb.ts_name }}` (symbol `{{ cb.vtable_init_symbol }}`). "
        "The trampoline impls are emitted; the vtable struct shape "
        "lookup is a follow-up codegen pass.\n");
}

} // namespace margelo::nitro::{{ module.namespace }}
