// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// C++ trampoline class for uniffi callback interface `{{ cb.ts_name }}`
// in crate `{{ module.crate_name }}`. JS implements the methods via a
// Nitro HybridObject subclass; this file's trampoline functions are what
// Rust calls *through* — they look up the JS-side instance by handle
// and invoke the matching method.
//
// The user code creates the foreign HybridObject in JS, then passes it
// as an argument to a uniffi method. The generated argument-lowering
// expression registers the shared_ptr with
// `CallbackHandleMap<{{ cb.cxx_class }}>` and hands the resulting
// uint64 handle to Rust. On first such registration we also ensure
// the vtable has been installed (`ensure_{{ cb.ts_name }}_vtable_init`).
#pragma once

#include <NitroModules/HybridObject.hpp>
#include <NitroModules/Promise.hpp>
#include <NitroUniffi.hpp>
#include <nitro-uniffi/foreign_future.hpp>
#include <nitro-uniffi/js_async_callback.hpp>
#include <nitro-uniffi/jsi_converter_ints.hpp>
#include <nitro-uniffi/jsi_converter_map.hpp>

#include <functional>
#include <memory>
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>

// Record / enum headers needed as complete types in method signatures.
{%- for header in cb.value_dependency_headers() %}
#include "{{ header }}"
{%- endfor %}

// Interface parameters/returns appear only behind `std::shared_ptr`, so a
// forward declaration suffices (and avoids circular includes); the full
// header is included in the `.cpp`.
{%- for fd in cb.interface_forward_decls() %}
namespace margelo::nitro::{{ fd.namespace }} { class {{ fd.cxx_class }}; }
{%- endfor %}

{%- if let Some(proxy) = cb.proxy %}
extern "C" {
// Rust-side reference management for a `with_foreign` trait object Rust
// can hand back as `Arc<dyn Trait>` (the proxy path).
void {{ proxy.free_symbol }}(uint64_t handle, UniffiRustCallStatus* status);
}
{%- endif %}

namespace margelo::nitro::{{ module.namespace }} {

// Forward declaration so the class's inline `ensure_vtable()` can name the
// per-callback init hook (defined out-of-line, after the class).
void ensure_{{ cb.ts_name }}_vtable_init();

/// Trampoline HybridObject for `{{ cb.ts_name }}`. The methods are
/// virtual so a JS-implementing HybridObject subclass can override them;
/// the default impls throw if the JS side hasn't supplied an override.
class {{ cb.cxx_class }} : public ::margelo::nitro::HybridObject {
public:
  static constexpr auto TAG = "{{ cb.ts_name }}";

{%- if let Some(proxy) = cb.proxy %}
  // Foreign-implemented (JS subclass) default constructor — no proxy handle.
  {{ cb.cxx_class }}() : HybridObject(TAG), proxy_handle_() {}
  // Rust-backed proxy constructor: wraps an `Arc<dyn Trait>` handle Rust
  // returned. Its methods (unless overridden by a JS subclass) dispatch back
  // into Rust; the handle is RAII-freed via the trait's uniffi free symbol.
  explicit {{ cb.cxx_class }}(::ubrn::nitro::FromRustHandle __h)
      : HybridObject(TAG), proxy_handle_(__h.raw) {}
{%- else %}
  {{ cb.cxx_class }}() : HybridObject(TAG) {}
{%- endif %}

{%- for method in cb.methods %}
  virtual {{ method.cxx_return_signature() }} {{ method.cxx_name }}(
{%- for arg in method.args -%}
    {{ arg.ty.cxx_type() }} {{ arg.ts_name }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  );
{%- endfor %}

{%- if cb.has_js_impl_methods() %}
  // JS-implementation setter. JS code creates a `{{ cb.cxx_class }}` via
  // `NitroModules.createHybridObject('{{ cb.ts_name }}')` then calls this
  // once with one function per trait method (the consumer-facing
  // `{{ cb.ts_name }}(...)` factory in the `.ts` module does this), binding
  // the JS impl. Nitro's `JSIConverter<std::function<...>>` turns each JS
  // function into a `SyncJSCallback`, so the virtuals below invoke JS
  // directly. A sync method runs inline and returns its value; an async
  // method returns `std::shared_ptr<ForeignAsyncResult<T>>` — the
  // `SyncJSCallback` converts the JS method's returned JS Promise via the
  // wrapper's `JSIConverter` (`nitro-uniffi/js_async_callback.hpp`), which
  // chains `.then`/`.catch` and yields the C++ `Promise<T>` the async
  // trampoline awaits. (A `Promise`-typed bound function would instead make
  // Nitro build an `AsyncJSCallback` that mis-reads the JS Promise as the raw
  // value — see `NitroCallbackMethod::cxx_return_signature`.)
  void setJsImpl(
{%- for method in cb.js_impl_methods() -%}
    std::function<{{ method.cxx_return_signature() }}(
{%- for arg in method.args -%}
      {{ arg.ty.cxx_type() }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
    )> {{ method.cxx_name }}_fn{% if !loop.last %}, {% endif %}
{%- endfor -%}
  );
{%- endif %}

  // Install this callback's vtable with Rust (idempotent). Generic handle
  // codecs (`ubrn::nitro::write_callback_handle{,_w}`) call this before the
  // first hand-off without needing to name the per-type free hook.
  static void ensure_vtable() { ensure_{{ cb.ts_name }}_vtable_init(); }

  // Turn this instance into the `uint64_t` handle Rust names it by. A
  // JS-implemented instance is registered with the per-type
  // `CallbackHandleMap` (which takes shared ownership via `self`, so the
  // instance stays alive while Rust holds the handle); a Rust-backed proxy
  // clones its existing Rust handle (uniffi consumes one reference per
  // hand-off). `self` is this same instance as a `shared_ptr` (the codecs
  // hold one already), passed so the map can co-own it.
  uint64_t lower_to_handle(const std::shared_ptr<{{ cb.cxx_class }}>& self);

protected:
  void loadHybridMethods() override;

private:
{%- if let Some(proxy) = cb.proxy %}
  // Non-zero when this instance is a Rust-backed proxy (Rust returned the
  // trait object); zero for a JS-implemented instance. RAII-frees via the
  // trait's uniffi free symbol on destruction.
  ubrn::nitro::UniffiObjectHandle<&{{ proxy.free_symbol }}> proxy_handle_;
{%- endif %}
  // The JS impl, bound by `setJsImpl`. Empty until then; a JS-implemented
  // instance always binds these before being handed to Rust. Each
  // JS-impl-supported method's virtual prefers this over the proxy / throw
  // paths. (Async-void methods are excluded — see `supports_js_impl`.)
{%- for method in cb.js_impl_methods() %}
  std::function<{{ method.cxx_return_signature() }}(
{%- for arg in method.args -%}
    {{ arg.ty.cxx_type() }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  )> {{ method.cxx_name }}_fn_;
{%- endfor %}
};

/// Idempotent vtable installation. Called from
/// `{{ module.namespace_api_cxx_class() }}` / `{{ cb.cxx_class }}` lowering
/// paths before the first cross-FFI hand-off. The actual vtable struct
/// shape varies per-callback (it's an FfiStruct with one function
/// pointer per method plus a clone + free entry); we surface the init
/// hook here and fill it in via a generated `.cpp` companion.
void ensure_{{ cb.ts_name }}_vtable_init();

} // namespace margelo::nitro::{{ module.namespace }}
