// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// C++ trampoline class for uniffi callback interface `{{ cb.ts_name }}`
// in crate `{{ module.crate_name }}`. JS implements the methods via a
// Nitro HybridObject subclass; this file's trampoline functions are what
// Rust calls *through* — they look up the JS-side instance by handle
// and invoke the matching method.
//
// The user code creates the foreign HybridObject in JS, then passes it
// as an argument to a uniffi method. The generated argument-lowering
// expression registers the shared_ptr with
// `CallbackHandleMap<{{ cb.cxx_class }}>` and hands the resulting
// uint64 handle to Rust. On first such registration we also ensure
// the vtable has been installed (`ensure_{{ cb.ts_name }}_vtable_init`).
#pragma once

#include <NitroModules/HybridObject.hpp>
#include <NitroUniffi.hpp>

namespace margelo::nitro::{{ module.namespace }} {

/// Trampoline HybridObject for `{{ cb.ts_name }}`. The methods are
/// virtual so a JS-implementing HybridObject subclass can override them;
/// the default impls throw if the JS side hasn't supplied an override.
class {{ cb.cxx_class }} : public ::margelo::nitro::HybridObject {
public:
  static constexpr auto TAG = "{{ cb.ts_name }}";

  {{ cb.cxx_class }}() : HybridObject(TAG) {}

{%- for method in cb.methods %}
  virtual {{ method.return_kind.cxx_type() }} {{ method.cxx_name }}(
{%- for arg in method.args -%}
    {{ arg.ty.cxx_type() }} {{ arg.ts_name }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  );
{%- endfor %}

protected:
  void loadHybridMethods() override;
};

/// Idempotent vtable installation. Called from
/// `{{ module.namespace_api_cxx_class() }}` / `{{ cb.cxx_class }}` lowering
/// paths before the first cross-FFI hand-off. The actual vtable struct
/// shape varies per-callback (it's an FfiStruct with one function
/// pointer per method plus a clone + free entry); we surface the init
/// hook here and fill it in via a generated `.cpp` companion.
void ensure_{{ cb.ts_name }}_vtable_init();

} // namespace margelo::nitro::{{ module.namespace }}
