// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// C++ trampoline impl for uniffi callback interface `{{ cb.ts_name }}`
// in crate `{{ module.crate_name }}`.
//
// Wiring overview:
//
//   1. JS code creates a `{{ cb.cxx_class }}` subclass and hands it
//      to a method that takes a `{{ cb.ts_name }}` parameter.
//   2. The generated lowering expression calls
//      `ensure_{{ cb.ts_name }}_vtable_init()` (installs the vtable once)
//      then `CallbackHandleMap<{{ cb.cxx_class }}>::instance().insert(...)`,
//      yielding a `uint64_t` handle handed to Rust.
//   3. Rust dispatches into our vtable trampolines below (one per method)
//      via that handle, plus clone/free for lifetime management.
//
// The vtable struct + ABI mirror uniffi 0.31's `UniFfiTraitVtable<Name>`
// (uniffi_macros `export/callback_interface.rs`): repr(C) field order is
// `uniffi_free`, `uniffi_clone`, then one fn-ptr per method in declaration
// order. Each method fn is
//   extern "C" void(uint64_t handle, <lowered args...>,
//                   <Ret>* uniffi_out_return, RustCallStatus* uniffi_out_call_status)
// i.e. the return value is written through an out-pointer and the fn itself
// returns void (a void-returning method still takes a `&mut ()` out slot).

#include "{{ cb.cxx_class }}.hpp"

#include <atomic>
#include <stdexcept>

extern "C" {
RustBuffer {{ module.rustbuffer_alloc }}(uint64_t size, UniffiRustCallStatus* status);
void {{ module.rustbuffer_free }}(RustBuffer buf, UniffiRustCallStatus* status);
RustBuffer {{ module.rustbuffer_reserve }}(RustBuffer buf, uint64_t add, UniffiRustCallStatus* status);
/// Rust-side hook: installs the vtable. Takes `NonNull<UniFfiTraitVtable…>`;
/// ABI is a plain non-null pointer, so we hand it `&our_vtable`.
void {{ cb.vtable_init_symbol }}(const void* vtable);
}

namespace margelo::nitro::{{ module.namespace }} {

namespace {
inline void free_status_buffer(RustBuffer buf) noexcept {
  UniffiRustCallStatus s{};
  {{ module.rustbuffer_free }}(buf, &s);
}
} // namespace

void {{ cb.cxx_class }}::loadHybridMethods() {
  HybridObject::loadHybridMethods();
  registerHybrids(this, [](Prototype& prototype) {
{%- for method in cb.methods %}
    prototype.registerHybridMethod("{{ method.ts_name }}", &{{ cb.cxx_class }}::{{ method.cxx_name }});
{%- endfor %}
  });
}

{% for method in cb.methods %}
{{ method.return_kind.cxx_type() }} {{ cb.cxx_class }}::{{ method.cxx_name }}(
{%- for arg in method.args -%}
    {{ arg.ty.cxx_type() }} /* {{ arg.ts_name }} */{% if !loop.last %}, {% endif %}
{%- endfor -%}
) {
  throw std::runtime_error(
      "{{ cb.ts_name }}::{{ method.cxx_name }} not implemented — "
      "this method must be overridden by a JS-side HybridObject subclass");
}
{% endfor %}

namespace {

using HandleMap = ubrn::nitro::CallbackHandleMap<{{ cb.cxx_class }}>;

// Per-method trampolines. uniffi calls these through the vtable with the
// handle + lowered args + an out-return pointer + a status out-param. We
// look up the JS-side instance, lift each arg (freeing any RustBuffer arg
// Rust handed us), invoke the method, and write the lowered result through
// `uniffi_out_return`. JS-side exceptions surface as code=2 (unexpected).
{% for method in cb.methods %}
extern "C" void {{ cb.ts_name }}_trampoline_{{ method.cxx_name }}(
    uint64_t self_handle
{%- for arg in method.args %},
    {{ arg.ty.c_type() }} {{ arg.ts_name }}_lowered
{%- endfor %},
{%- match method.return_kind %}
{%- when crate::bindings::gen_nitro::model::ReturnKind::Void %}
    void* /* uniffi_out_return (&mut ()) */,
{%- when crate::bindings::gen_nitro::model::ReturnKind::Value with (ret_ty) %}
    {{ ret_ty.c_type() }}* uniffi_out_return,
{%- endmatch %}
    UniffiRustCallStatus* uniffi_out_call_status
) {
    try {
        auto self = HandleMap::instance().get(self_handle);
{%- for arg in method.args %}
        auto {{ arg.ts_name }} = {{ arg.lifted_from_lowered_expr() }};
{%- if arg.ty.is_rust_buffer() %}
        // Rust handed us ownership of this arg buffer; the lift copied it
        // out, so free it now (exactly once).
        free_status_buffer({{ arg.ts_name }}_lowered);
{%- endif %}
{%- endfor %}
{%- match method.return_kind %}
{%- when crate::bindings::gen_nitro::model::ReturnKind::Void %}
        self->{{ method.cxx_name }}(
{%- for arg in method.args -%}
            {{ arg.ts_name }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
        );
{%- when crate::bindings::gen_nitro::model::ReturnKind::Value with (ret_ty) %}
        auto __out = self->{{ method.cxx_name }}(
{%- for arg in method.args -%}
            {{ arg.ts_name }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
        );
        *uniffi_out_return = {{ ret_ty.lower_expr("__out", module.rustbuffer_alloc, module.rustbuffer_reserve) }};
{%- endmatch %}
        uniffi_out_call_status->code = 0;
    } catch (const std::exception& e) {
        // Surface JS-side exceptions back to Rust as unexpected errors
        // (code=2). On error the out-return is left unwritten; Rust does
        // not read it. A follow-up pass can route typed uniffi errors.
        (void)e;
        uniffi_out_call_status->code = 2;
        uniffi_out_call_status->error_buf = RustBuffer{};
    }
}
{% endfor %}

/// Clone trampoline (`uniffi_clone`): Rust wants another reference to the
/// same foreign instance. The handle map stores a `shared_ptr`, so we look
/// it up and re-insert. No status param in uniffi's vtable ABI.
extern "C" uint64_t {{ cb.ts_name }}_trampoline_clone(uint64_t handle) {
    auto self = HandleMap::instance().get(handle);
    return HandleMap::instance().insert(self);
}

/// Free trampoline (`uniffi_free`): Rust calls this once per insert. No
/// status param in uniffi's vtable ABI.
extern "C" void {{ cb.ts_name }}_trampoline_free(uint64_t handle) {
    HandleMap::instance().remove(handle);
}

// repr(C) mirror of uniffi 0.31's `UniFfiTraitVtable{{ cb.ts_name }}`. Field
// *names* are irrelevant to the C ABI (the struct is positional); only the
// order (free, clone, then methods) and the per-field fn-ptr signatures
// matter. Kept in lock-step with `export/callback_interface.rs`.
struct {{ cb.ts_name }}VTable {
  void (*uniffi_free)(uint64_t);
  uint64_t (*uniffi_clone)(uint64_t);
{%- for method in cb.methods %}
  void (*{{ method.cxx_name }})(uint64_t
{%- for arg in method.args %}, {{ arg.ty.c_type() }}{% endfor %},
{%- match method.return_kind %}
{%- when crate::bindings::gen_nitro::model::ReturnKind::Void %} void*
{%- when crate::bindings::gen_nitro::model::ReturnKind::Value with (ret_ty) %} {{ ret_ty.c_type() }}*
{%- endmatch %}, UniffiRustCallStatus*);
{%- endfor %}
};

} // namespace

void ensure_{{ cb.ts_name }}_vtable_init() {
    // Idempotent: install the vtable at most once per process. The static
    // instance outlives the runtime, so the function pointers stay valid.
    static std::atomic<bool> installed{false};
    bool expected = false;
    if (!installed.compare_exchange_strong(expected, true)) {
        return;
    }
    static {{ cb.ts_name }}VTable vtable = {
        &{{ cb.ts_name }}_trampoline_free,
        &{{ cb.ts_name }}_trampoline_clone,
{%- for method in cb.methods %}
        &{{ cb.ts_name }}_trampoline_{{ method.cxx_name }},
{%- endfor %}
    };
    {{ cb.vtable_init_symbol }}(&vtable);
}

} // namespace margelo::nitro::{{ module.namespace }}
