// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// Per-record / per-enum codecs for uniffi namespace `{{ module.namespace }}`.
//
// Records and enums cross the uniffi C ABI as a `RustBuffer`. The
// field-by-field wire format is big-endian (see uniffi-rs's
// `lower_into_buffer`); the `RustBufferReader` / `RustBufferWriter`
// helpers in `<NitroUniffi.hpp>` handle each primitive.
//
// Nitrogen auto-emits the C++ struct for every record interface in
// `{{ module.namespace_camel }}.nitro.ts` and the discriminated union
// for every flat enum, so this header just needs to declare the
// `lift_<Name>` / `lower_<Name>` free functions. The generated
// `Hybrid<Namespace>Api.cpp` includes this header to get the lift/lower
// expressions used in each method body's argument lowering.
#pragma once

#include <NitroUniffi.hpp>

{%- for record in module.records %}
#include "{{ record.ts_name }}.hpp"
{%- endfor %}
{%- for en in module.enums %}
#include "{{ en.ts_name }}.hpp"
{%- endfor %}

extern "C" {
RustBuffer {{ module.rustbuffer_alloc }}(uint64_t size, UniffiRustCallStatus* status);
RustBuffer {{ module.rustbuffer_reserve }}(RustBuffer buf, uint64_t add, UniffiRustCallStatus* status);
}

namespace margelo::nitro::{{ module.namespace }} {

{%- for record in module.records %}

// ---- Record `{{ record.ts_name }}` ----
inline {{ record.ts_name }} lift_{{ record.ts_name }}(RustBuffer buf) {
{%- if record.codec_ready %}
  ::ubrn::nitro::RustBufferReader __reader(buf);
  {{ record.ts_name }} __out{};
{%- for field in record.fields %}
  __out.{{ field.ts_name }} = __reader.read_{{ field.ty.rb_suffix() }}();
{%- endfor %}
  return __out;
{%- else %}
  // Codec generation skipped — at least one field of `{{ record.ts_name }}`
  // uses a uniffi type the Nitro backend doesn't yet model (Optional /
  // Sequence / Map / Interface / Bytes). Calling this lifter at runtime
  // is a programming error.
  (void)buf;
  throw std::runtime_error("lift_{{ record.ts_name }}: codec not yet emitted");
{%- endif %}
}

inline RustBuffer lower_{{ record.ts_name }}(const {{ record.ts_name }}& value) {
{%- if record.codec_ready %}
  ::ubrn::nitro::RustBufferWriter<&{{ module.rustbuffer_alloc }}, &{{ module.rustbuffer_reserve }}> __writer;
{%- for field in record.fields %}
  __writer.write_{{ field.ty.rb_suffix() }}(value.{{ field.ts_name }});
{%- endfor %}
  return __writer.finish();
{%- else %}
  (void)value;
  throw std::runtime_error("lower_{{ record.ts_name }}: codec not yet emitted");
{%- endif %}
}
{%- endfor %}

{%- for en in module.enums %}

// ---- Enum `{{ en.ts_name }}` ----
inline {{ en.ts_name }} lift_{{ en.ts_name }}(RustBuffer buf) {
{%- if en.flat %}
  ::ubrn::nitro::RustBufferReader __reader(buf);
  int32_t __ordinal = __reader.read_i32();
  switch (__ordinal) {
{%- for variant in en.variants %}
    case {{ loop.index }}: return {{ en.ts_name }}::{{ variant.ts_name }};
{%- endfor %}
    default:
      throw std::runtime_error("lift_{{ en.ts_name }}: unknown ordinal");
  }
{%- else %}
  (void)buf;
  throw std::runtime_error("lift_{{ en.ts_name }}: tagged-enum codecs not yet emitted");
{%- endif %}
}

inline RustBuffer lower_{{ en.ts_name }}(const {{ en.ts_name }}& value) {
{%- if en.flat %}
  ::ubrn::nitro::RustBufferWriter<&{{ module.rustbuffer_alloc }}, &{{ module.rustbuffer_reserve }}> __writer;
  int32_t __ordinal = 0;
  switch (value) {
{%- for variant in en.variants %}
    case {{ en.ts_name }}::{{ variant.ts_name }}: __ordinal = {{ loop.index }}; break;
{%- endfor %}
  }
  __writer.write_i32(__ordinal);
  return __writer.finish();
{%- else %}
  (void)value;
  throw std::runtime_error("lower_{{ en.ts_name }}: tagged-enum codecs not yet emitted");
{%- endif %}
}
{%- endfor %}

{%- for err in module.errors %}

// ---- Error `{{ err.ts_name }}` ----
//
// One C++ exception class per uniffi `EnumShape::Error`. The `kind`
// field carries the variant tag. Method bodies that declare
// `throws({{ err.ts_name }})` decode the status RustBuffer via
// `{{ err.lift_fn() }}` and rethrow as `{{ err.cxx_class() }}`; Nitro's
// HybridFunction::callMethod then translates the C++ throw into a
// `jsi::JSError` on the JS side.
enum class {{ err.cxx_class() }}Kind : int32_t {
{%- for variant in err.variants %}
  {{ variant.ts_name }} = {{ loop.index }},
{%- endfor %}
};

class {{ err.cxx_class() }} : public std::runtime_error {
public:
  explicit {{ err.cxx_class() }}({{ err.cxx_class() }}Kind kind, const std::string& message)
      : std::runtime_error(message), kind(kind) {}
  {{ err.cxx_class() }}Kind kind;
};

inline {{ err.cxx_class() }} {{ err.lift_fn() }}(RustBuffer buf) {
  // Decode only the variant tag — the associated fields (if any) are
  // currently dropped. That's fine for the unit-variant errors uniffi
  // emits when `#[derive(uniffi::Error)]` is the only attribute on the
  // Rust enum (which is the common case); enums whose variants carry
  // data lose that data on the JS side until the tagged-variant codec
  // lands.
  ::ubrn::nitro::RustBufferReader __reader(buf);
  int32_t __ordinal = __reader.read_i32();
  switch (__ordinal) {
{%- for variant in err.variants %}
    case {{ loop.index }}: return {{ err.cxx_class() }}({{ err.cxx_class() }}Kind::{{ variant.ts_name }}, "{{ err.ts_name }}::{{ variant.ts_name }}");
{%- endfor %}
    default:
      throw std::runtime_error("{{ err.lift_fn() }}: unknown variant ordinal");
  }
}
{%- endfor %}

} // namespace margelo::nitro::{{ module.namespace }}
