// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// Per-record / per-enum codecs for uniffi namespace `{{ module.namespace }}`.
//
// Records and enums cross the uniffi C ABI as a `RustBuffer`. The
// field-by-field wire format is big-endian (see uniffi-rs's
// `lower_into_buffer`); the `RustBufferReader` / `RustBufferWriter`
// helpers in `<NitroUniffi.hpp>` handle each primitive, and the composite
// thunks in `nitro-uniffi/composites.hpp` handle Option / Vec / Map /
// Bytes / interface-handle field types — recursively.
//
// ubrn emits the C++ struct (records) / `std::variant` representation
// (tagged enums) / `enum class` (flat enums) plus their `JSIConverter`
// specializations into the per-type `<Name>.hpp` headers included below.
// This file then layers the RustBuffer codec on top:
//
//   * `write_<Name>(RustBufferWriter&, const <Name>&)` /
//     `read_<Name>(RustBufferReader&) -> <Name>` — the *stream* codec.
//     These have the uniform `(writer, value)` / `(reader) -> value`
//     signature the composite thunks expect, so a record / enum nests
//     inside any Option / Vec / Map (and recursively into itself) just by
//     handing `&write_<Name>` / `&read_<Name>` as the per-element thunk.
//
//   * `lower_<Name>(const <Name>&) -> RustBuffer` /
//     `lift_<Name>(RustBuffer) -> <Name>` — thin top-level wrappers that
//     own the `RustBuffer` lifecycle for the FFI boundary; both delegate
//     to the stream codec.
//
// Forward declarations of every stream codec are emitted first so mutually
// recursive types (`Tree { Node { children: Vec<Tree> } }`) resolve.
#pragma once

#include <NitroUniffi.hpp>

{%- for record in module.records %}
#include "{{ record.ts_name }}.hpp"
{%- endfor %}
{%- for en in module.enums %}
#include "{{ en.ts_name }}.hpp"
{%- endfor %}
{#- Foreign namespaces' codecs. A field / arg / return typed as a record or
    enum from another uniffi namespace calls that namespace's
    `::margelo::nitro::<foreign_ns>::{write,read,lower,lift}_<Name>`, which is
    declared in its own `<foreign_ns>_codecs.hpp`. Cross-namespace generation
    emits every namespace into this same directory, so it's a plain include. #}
{%- for header in module.foreign_codec_headers() %}
#include "{{ header }}"
{%- endfor %}

extern "C" {
RustBuffer {{ module.rustbuffer_alloc }}(uint64_t size, UniffiRustCallStatus* status);
RustBuffer {{ module.rustbuffer_reserve }}(RustBuffer buf, uint64_t add, UniffiRustCallStatus* status);
void {{ module.rustbuffer_free }}(RustBuffer buf, UniffiRustCallStatus* status);
}

namespace margelo::nitro::{{ module.namespace }} {

// Make the base `ubrn::nitro::error_field_to_string` scalar / composite
// overloads (`error_message.hpp`) visible by unqualified name in this
// namespace, so the record/enum overloads below — and the error lifter's
// `error_field_to_string(__f)` call — resolve a scalar field through them while
// a record/enum field resolves to a same-namespace overload here (audit bug #29).
using ::ubrn::nitro::error_field_to_string;

// Namespace-local writer type: this namespace's top-level `lower_<Name>`
// wrappers allocate through its own `rustbuffer_alloc` / `rustbuffer_reserve`
// symbols.
using Writer =
    ::ubrn::nitro::RustBufferWriter<&{{ module.rustbuffer_alloc }}, &{{ module.rustbuffer_reserve }}>;
using ::ubrn::nitro::RustBufferReader;

// Hands an error / unexpected-error RustBuffer back to Rust's allocator.
// One definition per namespace here (this header is #pragma once and is
// #included by every impl .cpp), so the per-object .cpp can be #include-
// amalgamated into a single iOS unity TU without colliding.
inline void free_status_buffer(RustBuffer buf) noexcept {
  UniffiRustCallStatus s{};
  {{ module.rustbuffer_free }}(buf, &s);
}

// The per-type `write_<Name>` stream codec is *templated on the writer type
// `W`* (any `RustBufferWriter<Alloc, Reserve>` instantiation). This is what
// makes a record / enum from this namespace serialize straight into another
// namespace's outer buffer when it appears as a cross-namespace field: that
// foreign codec calls `::margelo::nitro::<this_ns>::write_<Name>(foreign_w, …)`
// and `W` is deduced as the *foreign* writer. The field walk therefore uses
// the writer-generic `*_w` composite thunks (see `nitro-uniffi/composites.hpp`)
// rather than ones pinned to this namespace's allocator symbols. `read_<Name>`
// needs no such treatment — `RustBufferReader` is namespace-independent.

// ---- Forward declarations (mutual recursion) ----
{%- for record in module.records %}
template <class W> inline void write_{{ record.ts_name }}(W& w, const {{ record.ts_name }}& value);
inline {{ record.ts_name }} read_{{ record.ts_name }}(RustBufferReader& r);
{%- endfor %}
{%- for en in module.enums %}
template <class W> inline void write_{{ en.ts_name }}(W& w, const {{ en.ts_name }}& value);
inline {{ en.ts_name }} read_{{ en.ts_name }}(RustBufferReader& r);
{%- endfor %}

// ---- `error_field_to_string(const <Record/Enum>&)` overloads (audit bug #29) ----
//
// A data-carrying uniffi error variant whose payload field is itself a record
// or (data / flat) enum is now rendered into the exception message (see
// `NitroType::is_error_message_decodable`, which allows Record / Enum exactly
// because these overloads exist). They MUST live in this type's own namespace,
// not `ubrn::nitro`: the base `ubrn::nitro::error_field_to_string(const
// std::vector<T>&)` / `optional<T>` composite templates recurse with an
// *unqualified* call resolved by ADL at instantiation — and ADL on a
// `std::vector<{{ module.namespace }}::Foo>` only searches `{{ module.namespace }}`,
// not `ubrn::nitro`. Placing the overloads here makes a `Vec<record/enum>` /
// `Option<record/enum>` error field compile (e.g. a recursive `Tree`). The
// bodies call unqualified `error_field_to_string`: a scalar field resolves via
// the `using ::ubrn::nitro::error_field_to_string` above, a nested record/enum
// via these same-namespace overloads, a composite via the ADL-reachable
// `ubrn::nitro` templates. Forward-declared first for mutual recursion; emitted
// for every record / enum (an unused one is a harmless inline).
{%- for record in module.records %}
inline std::string error_field_to_string(const {{ record.ts_name }}& value);
{%- endfor %}
{%- for en in module.enums %}
inline std::string error_field_to_string(const {{ en.ts_name }}& value);
{%- endfor %}

{%- for record in module.records %}
inline std::string error_field_to_string(const {{ record.ts_name }}& value) {
  std::string __out = "{{ record.ts_name }}{";
  bool __first = true;
{%- for field in record.fields %}
  if (!__first) { __out += ", "; }
  __first = false;
  __out += "{{ field.ts_name }}=";
  __out += error_field_to_string(value.{{ field.cxx_name }});
{%- endfor %}
  __out += "}";
  (void)__first;
  return __out;
}
{%- endfor %}
{%- for en in module.enums %}
{%- if en.flat %}
inline std::string error_field_to_string(const {{ en.ts_name }}& value) {
  switch (value) {
{%- for variant in en.variants %}
    case {{ en.ts_name }}::{{ variant.ts_name }}: return "{{ en.ts_name }}::{{ variant.ts_name }}";
{%- endfor %}
  }
  return "{{ en.ts_name }}::<unknown>";
}
{%- else %}
inline std::string error_field_to_string(const {{ en.ts_name }}& value) {
  switch (value.variant.index()) {
{%- for variant in en.variants %}
    case {{ loop.index0 }}: {
      std::string __out = "{{ en.ts_name }}::{{ variant.ts_name }}";
{%- if !variant.fields.is_empty() %}
      const auto& __v = std::get<{{ loop.index0 }}>(value.variant);
      __out += "(";
      bool __first = true;
{%- for field in variant.fields %}
      if (!__first) { __out += ", "; }
      __first = false;
{%- if !field.ts_name.is_empty() %}
      __out += "{{ field.ts_name }}=";
{%- endif %}
      __out += error_field_to_string(__v.{{ field.cxx_name }});
{%- endfor %}
      __out += ")";
      (void)__first;
{%- endif %}
      return __out;
    }
{%- endfor %}
    default:
      return "{{ en.ts_name }}::<unknown>";
  }
}
{%- endif %}
{%- endfor %}

{%- for record in module.records %}

// ---- Record `{{ record.ts_name }}` ----
template <class W>
inline void write_{{ record.ts_name }}(W& w, const {{ record.ts_name }}& value) {
{%- if record.fixed_prefix_width() > 0 %}
  // Reserve the leading fixed-width fields' bytes up front (capacity only; the
  // wire bytes written are unchanged).
  w.reserve_additional({{ record.fixed_prefix_width() }});
{%- endif %}
{%- for field in record.fields %}
  {{ field.ty.stream_write_stmt("value", field.cxx_name, module.namespace) }}
{%- endfor %}
  (void)w;
  (void)value;
}

inline {{ record.ts_name }} read_{{ record.ts_name }}(RustBufferReader& r) {
  {{ record.ts_name }} __out{};
{%- for field in record.fields %}
  __out.{{ field.cxx_name }} = {{ field.ty.stream_read_expr(module.namespace) }};
{%- endfor %}
  (void)r;
  return __out;
}

inline RustBuffer lower_{{ record.ts_name }}(const {{ record.ts_name }}& value) {
  Writer w;
  write_{{ record.ts_name }}(w, value);
  return w.finish();
}

inline {{ record.ts_name }} lift_{{ record.ts_name }}(RustBuffer buf) {
  RustBufferReader r{buf};
  return read_{{ record.ts_name }}(r);
}
{%- endfor %}

{%- for en in module.enums %}

// ---- Enum `{{ en.ts_name }}` ----
{%- if en.flat %}
template <class W>
inline void write_{{ en.ts_name }}(W& w, const {{ en.ts_name }}& value) {
  int32_t __ordinal = 0;
  switch (value) {
{%- for variant in en.variants %}
    case {{ en.ts_name }}::{{ variant.ts_name }}: __ordinal = {{ loop.index }}; break;
{%- endfor %}
  }
  w.write_i32(__ordinal);
}

inline {{ en.ts_name }} read_{{ en.ts_name }}(RustBufferReader& r) {
  int32_t __ordinal = r.read_i32();
  switch (__ordinal) {
{%- for variant in en.variants %}
    case {{ loop.index }}: return {{ en.ts_name }}::{{ variant.ts_name }};
{%- endfor %}
    default:
      throw std::runtime_error("read_{{ en.ts_name }}: unknown ordinal");
  }
}
{%- else %}
template <class W>
inline void write_{{ en.ts_name }}(W& w, const {{ en.ts_name }}& value) {
  // Wire format: i32 tag (1-based, in declaration order) then the variant's
  // fields in order. `value.variant` is a `std::variant` over the per-
  // variant payload structs; the index lines up with the tag.
  switch (value.variant.index()) {
{%- for variant in en.variants %}
    case {{ loop.index0 }}: {
      w.write_i32({{ loop.index }});
{%- if !variant.fields.is_empty() %}
      const auto& __v = std::get<{{ loop.index0 }}>(value.variant);
{%- for field in variant.fields %}
      {{ field.ty.stream_write_stmt("__v", field.cxx_name, module.namespace) }}
{%- endfor %}
{%- endif %}
      break;
    }
{%- endfor %}
    default:
      throw std::runtime_error("write_{{ en.ts_name }}: unknown variant index");
  }
}

inline {{ en.ts_name }} read_{{ en.ts_name }}(RustBufferReader& r) {
  int32_t __tag = r.read_i32();
  switch (__tag) {
{%- for variant in en.variants %}
    case {{ loop.index }}: {
      {{ variant.cxx_struct_name(en.ts_name) }} __v{};
{%- for field in variant.fields %}
      __v.{{ field.cxx_name }} = {{ field.ty.stream_read_expr(module.namespace) }};
{%- endfor %}
      return {{ en.ts_name }}{ {{ en.ts_name }}::Variant{std::move(__v)} };
    }
{%- endfor %}
    default:
      throw std::runtime_error("read_{{ en.ts_name }}: unknown tag");
  }
}
{%- endif %}

inline RustBuffer lower_{{ en.ts_name }}(const {{ en.ts_name }}& value) {
  Writer w;
  write_{{ en.ts_name }}(w, value);
  return w.finish();
}

inline {{ en.ts_name }} lift_{{ en.ts_name }}(RustBuffer buf) {
  RustBufferReader r{buf};
  return read_{{ en.ts_name }}(r);
}
{%- endfor %}

{%- for err in module.errors %}

// ---- Error `{{ err.ts_name }}` ----
//
// One C++ exception class per uniffi `EnumShape::Error`. The `kind`
// field carries the variant tag. Method bodies that declare
// `throws({{ err.ts_name }})` decode the status RustBuffer via
// `{{ err.lift_fn() }}` and rethrow as `{{ err.cxx_class() }}`; Nitro's
// HybridFunction::callMethod then translates the C++ throw into a
// `jsi::JSError` on the JS side.
//
// Non-flat error variants carry data: uniffi serializes them as an i32 tag
// (1-based, declaration order) followed by the variant's fields in order —
// the exact tagged data-enum wire format (uniffi_macros
// `rich_error_ffi_converter_impl`). `{{ err.lift_fn() }}` reads those fields
// back off the wire and folds their rendered values into both the exception
// `payload` member (for native C++ consumers) and the `what()` message
// (which is the *only* channel Nitro hands to `jsi::JSError`, so JS sees the
// payload via `error.message`). Fields whose type can't be rendered (records,
// data enums, interface handles, or — notably — another error enum used as a
// field, which has no value reader) fall back to the tag-only message.
enum class {{ err.cxx_class() }}Kind : int32_t {
{%- for variant in err.variants %}
  {{ variant.ts_name }} = {{ loop.index }},
{%- endfor %}
};

class {{ err.cxx_class() }} : public std::runtime_error {
public:
  explicit {{ err.cxx_class() }}({{ err.cxx_class() }}Kind kind, const std::string& message)
      : std::runtime_error(message), kind(kind) {}
  explicit {{ err.cxx_class() }}({{ err.cxx_class() }}Kind kind, const std::string& message,
                                 std::string payload)
      : std::runtime_error(message), kind(kind), payload(std::move(payload)) {}
  {{ err.cxx_class() }}Kind kind;
  // Rendered associated-data fragment for data-carrying variants (empty for
  // unit variants and for variants whose fields aren't renderable). Mirrors
  // the trailing `(...)` already folded into `what()`.
  std::string payload;
};

inline {{ err.cxx_class() }} {{ err.lift_fn() }}(RustBuffer buf) {
  // Wire format: i32 variant tag (1-based) followed by the variant's fields
  // in declaration order — identical to a tagged data-enum.
  ::ubrn::nitro::RustBufferReader __reader(buf);
  int32_t __ordinal = __reader.read_i32();
  switch (__ordinal) {
{%- for variant in err.variants %}
{%- if variant.error_fields_surfaced() %}
    case {{ loop.index }}: {
      ::ubrn::nitro::RustBufferReader& r = __reader;
      std::string __payload;
{%- for field in variant.fields %}
      {
        auto __f = {{ field.ty.stream_read_expr(module.namespace) }};
        if (!__payload.empty()) {
          __payload += ", ";
        }
{%- if !field.ts_name.is_empty() %}
        __payload += "{{ field.ts_name }}=";
{%- endif %}
        __payload += error_field_to_string(__f);
      }
{%- endfor %}
      return {{ err.cxx_class() }}({{ err.cxx_class() }}Kind::{{ variant.ts_name }},
                                   "{{ err.ts_name }}::{{ variant.ts_name }}(" + __payload + ")",
                                   __payload);
    }
{%- else %}
    case {{ loop.index }}: return {{ err.cxx_class() }}({{ err.cxx_class() }}Kind::{{ variant.ts_name }}, "{{ err.ts_name }}::{{ variant.ts_name }}");
{%- endif %}
{%- endfor %}
    default:
      throw std::runtime_error("{{ err.lift_fn() }}: unknown variant ordinal");
  }
}
{%- endfor %}

} // namespace margelo::nitro::{{ module.namespace }}
