// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// C++ type + JSIConverter for uniffi enum `{{ en.ts_name }}` in namespace
// `{{ module.namespace }}`.
//
// Flat enums (no associated data) become an `enum class` surfaced to JS as
// a string union, mirroring Nitrogen. Tagged enums (data variants) become
// one payload struct per variant wrapped in a `std::variant`, surfaced to
// JS as a discriminated union `{ type: '<variant>', ...fields }`. Both get
// a hand-written `JSIConverter` so there is no dependency on Nitrogen.
#pragma once

#include <NitroModules/JSIConverter.hpp>
#include <NitroModules/JSIHelpers.hpp>
#include <NitroModules/NitroHash.hpp>
#include <NitroModules/PropNameIDCache.hpp>

#include <NitroUniffi.hpp>
#include <nitro-uniffi/jsi_converter_ints.hpp>
#include <nitro-uniffi/jsi_converter_map.hpp>

#include <optional>
#include <string>
#include <unordered_map>
#include <variant>
#include <vector>
{%- for header in en.dependency_headers() %}
#include "{{ header }}"
{%- endfor %}

namespace margelo::nitro::{{ module.namespace }} {

{%- if en.flat %}

/**
 * Uniffi flat enum `{{ en.ts_name }}` (JS string union).
 */
enum class {{ en.ts_name }} {
{%- for variant in en.variants %}
  {{ variant.ts_name }} = {{ loop.index0 }},
{%- endfor %}
};

{%- else %}

// Recursive / tagged enums reference themselves through `std::vector` /
// `std::optional` members, so forward-declare the wrapper before the
// per-variant payload structs that embed it.
struct {{ en.ts_name }};

{%- for variant in en.variants %}
/**
 * Payload for `{{ en.ts_name }}::{{ variant.ts_name }}`.
 */
struct {{ variant.cxx_struct_name(en.ts_name) }} final {
{%- for field in variant.fields %}
  {{ field.ty.cxx_type() }} {{ field.ts_name }};
{%- endfor %}
  friend bool operator==(const {{ variant.cxx_struct_name(en.ts_name) }}&, const {{ variant.cxx_struct_name(en.ts_name) }}&) = default;
};
{%- endfor %}

/**
 * Uniffi tagged enum `{{ en.ts_name }}` (JS discriminated union).
 */
struct {{ en.ts_name }} final {
  using Variant = std::variant<
{%- for variant in en.variants -%}
    {{ variant.cxx_struct_name(en.ts_name) }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  >;
  Variant variant;
  friend bool operator==(const {{ en.ts_name }}&, const {{ en.ts_name }}&) = default;
};

{%- endif %}

} // namespace margelo::nitro::{{ module.namespace }}

namespace margelo::nitro {

{%- if en.flat %}

// C++ {{ en.ts_name }} <> JS {{ en.ts_name }} (string union)
template <>
struct JSIConverter<margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}> final {
  static inline margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}
  fromJSI(jsi::Runtime& runtime, const jsi::Value& arg) {
    std::string unionValue = JSIConverter<std::string>::fromJSI(runtime, arg);
    switch (hashString(unionValue.c_str(), unionValue.size())) {
{%- for variant in en.variants %}
      case hashString("{{ variant.ts_name }}"): return margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}::{{ variant.ts_name }};
{%- endfor %}
      default: [[unlikely]]
        throw std::invalid_argument("Cannot convert \"" + unionValue + "\" to enum {{ en.ts_name }} - invalid value!");
    }
  }
  static inline jsi::Value
  toJSI(jsi::Runtime& runtime, margelo::nitro::{{ module.namespace }}::{{ en.ts_name }} arg) {
    switch (arg) {
{%- for variant in en.variants %}
      case margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}::{{ variant.ts_name }}: return JSIConverter<std::string>::toJSI(runtime, "{{ variant.ts_name }}");
{%- endfor %}
      default: [[unlikely]]
        throw std::invalid_argument("Cannot convert {{ en.ts_name }} to JS - invalid value: " + std::to_string(static_cast<int>(arg)) + "!");
    }
  }
  static inline bool canConvert(jsi::Runtime& runtime, const jsi::Value& value) {
    if (!value.isString()) {
      return false;
    }
    std::string unionValue = JSIConverter<std::string>::fromJSI(runtime, value);
    switch (hashString(unionValue.c_str(), unionValue.size())) {
{%- for variant in en.variants %}
      case hashString("{{ variant.ts_name }}"):
{%- endfor %}
        return true;
      default:
        return false;
    }
  }
};

{%- else %}

// C++ {{ en.ts_name }} <> JS {{ en.ts_name }} (discriminated union on `type`)
template <>
struct JSIConverter<margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}> final {
  using EnumT = margelo::nitro::{{ module.namespace }}::{{ en.ts_name }};

  static inline EnumT fromJSI(jsi::Runtime& runtime, const jsi::Value& arg) {
    jsi::Object obj = arg.asObject(runtime);
    std::string __tag = JSIConverter<std::string>::fromJSI(
        runtime, obj.getProperty(runtime, PropNameIDCache::get(runtime, "type")));
    switch (hashString(__tag.c_str(), __tag.size())) {
{%- for variant in en.variants %}
      case hashString("{{ variant.tag }}"): {
        margelo::nitro::{{ module.namespace }}::{{ variant.cxx_struct_name(en.ts_name) }} __v{};
{%- for field in variant.fields %}
        __v.{{ field.ts_name }} = JSIConverter<{{ field.ty.cxx_type() }}>::fromJSI(runtime, obj.getProperty(runtime, PropNameIDCache::get(runtime, "{{ field.ts_name }}")));
{%- endfor %}
        return EnumT{EnumT::Variant{std::move(__v)}};
      }
{%- endfor %}
      default: [[unlikely]]
        throw std::invalid_argument("Cannot convert \"" + __tag + "\" to enum {{ en.ts_name }} - invalid tag!");
    }
  }

  static inline jsi::Value toJSI(jsi::Runtime& runtime, const EnumT& arg) {
    jsi::Object obj(runtime);
    switch (arg.variant.index()) {
{%- for variant in en.variants %}
      case {{ loop.index0 }}: {
        obj.setProperty(runtime, PropNameIDCache::get(runtime, "type"), JSIConverter<std::string>::toJSI(runtime, "{{ variant.tag }}"));
{%- if !variant.fields.is_empty() %}
        const auto& __v = std::get<{{ loop.index0 }}>(arg.variant);
{%- for field in variant.fields %}
        obj.setProperty(runtime, PropNameIDCache::get(runtime, "{{ field.ts_name }}"), JSIConverter<{{ field.ty.cxx_type() }}>::toJSI(runtime, __v.{{ field.ts_name }}));
{%- endfor %}
{%- endif %}
        break;
      }
{%- endfor %}
      default: [[unlikely]]
        throw std::invalid_argument("Cannot convert {{ en.ts_name }} to JS - invalid variant index!");
    }
    return obj;
  }

  static inline bool canConvert(jsi::Runtime& runtime, const jsi::Value& value) {
    if (!value.isObject()) {
      return false;
    }
    jsi::Object obj = value.getObject(runtime);
    if (!obj.hasProperty(runtime, PropNameIDCache::get(runtime, "type"))) {
      return false;
    }
    jsi::Value __type = obj.getProperty(runtime, PropNameIDCache::get(runtime, "type"));
    if (!__type.isString()) {
      return false;
    }
    std::string __tag = __type.asString(runtime).utf8(runtime);
    switch (hashString(__tag.c_str(), __tag.size())) {
{%- for variant in en.variants %}
      case hashString("{{ variant.tag }}"):
{%- endfor %}
        return true;
      default:
        return false;
    }
  }
};

{%- endif %}

} // namespace margelo::nitro
