// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// C++ type + JSIConverter for uniffi enum `{{ en.ts_name }}` in namespace
// `{{ module.namespace }}`.
//
// Flat enums (no associated data) become an `enum class` surfaced to JS as
// a string union, mirroring Nitrogen. Tagged enums (data variants) become
// one payload struct per variant wrapped in a `std::variant`, surfaced to
// JS as a discriminated union `{ tag: '<VariantName>', inner: <payload> }` —
// the standard uniffi tagged-enum runtime shape (tag = the UpperCamelCase
// variant name; `inner` an object for named-field variants, a positional
// array for tuple variants; absent for unit variants). Both get a
// hand-written `JSIConverter` so there is no dependency on Nitrogen.
//
{%- if en.in_cycle() %}
// This enum is part of a record/enum header `#include` cycle. To stay
// compilable from either entry order we forward-declare the cycle partners,
// declare `JSIConverter<{{ en.ts_name }}>` here, pull the partner headers in
// *after* the struct, and define the converter out-of-line in the guarded
// `{{ en.ts_name }}.conv.hpp` footer — emitted only once every struct in the
// cycle is complete. See `NitroModule::resolve_cycles`.
{%- endif %}
#pragma once

#include <NitroModules/JSIConverter.hpp>
#include <NitroModules/JSIHelpers.hpp>
#include <NitroModules/NitroHash.hpp>
#include <NitroModules/PropNameIDCache.hpp>

#include <NitroUniffi.hpp>
#include <nitro-uniffi/interned_tag.hpp>
#include <nitro-uniffi/jsi_converter_ints.hpp>
#include <nitro-uniffi/jsi_converter_map.hpp>

#include <memory>
#include <optional>
#include <string>
#include <unordered_map>
#include <variant>
#include <vector>
{%- for header in en.dependency_headers() %}
#include "{{ header }}"
{%- endfor %}

namespace margelo::nitro::{{ module.namespace }} {

{%- if en.flat %}

/**
 * Uniffi flat enum `{{ en.ts_name }}` (JS string union).
 */
enum class {{ en.ts_name }} {
{%- for variant in en.variants %}
  {{ variant.ts_name }} = {{ loop.index0 }},
{%- endfor %}
};

{%- else %}

// Recursive / tagged enums reference themselves through `std::vector` /
// `std::optional` members, so forward-declare the wrapper before the
// per-variant payload structs that embed it.
struct {{ en.ts_name }};
{%- if en.in_cycle() %}
// Cycle partners reached only through `std::vector` / `std::optional` —
// forward-declared so the payload structs below can name them without pulling
// their mutually dependent headers in first. By-value partners (if any) are
// ordinary top `#include`s above.
{%- for partner in en.cycle_partners %}
{%- if !partner.by_value %}
struct {{ partner.name }};
{%- endif %}
{%- endfor %}
{%- endif %}

{%- for variant in en.variants %}
/**
 * Payload for `{{ en.ts_name }}::{{ variant.ts_name }}`.
 */
struct {{ variant.cxx_struct_name(en.ts_name) }} final {
{%- for field in variant.fields %}
  {{ field.ty.cxx_type() }} {{ field.cxx_name }};
{%- endfor %}
  friend bool operator==(const {{ variant.cxx_struct_name(en.ts_name) }}&, const {{ variant.cxx_struct_name(en.ts_name) }}&) = default;
};
{%- endfor %}

/**
 * Uniffi tagged enum `{{ en.ts_name }}` (JS discriminated union).
 */
struct {{ en.ts_name }} final {
  using Variant = std::variant<
{%- for variant in en.variants -%}
    {{ variant.cxx_struct_name(en.ts_name) }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  >;
  Variant variant;
  friend bool operator==(const {{ en.ts_name }}&, const {{ en.ts_name }}&) = default;
};

{%- endif %}

} // namespace margelo::nitro::{{ module.namespace }}

{%- if en.in_cycle() %}

// Mark this enum's struct complete for the cycle's converter guards.
#define UBRN_CYC_{{ module.namespace }}_{{ en.ts_name }}_STRUCT 1

namespace margelo::nitro {

// C++ {{ en.ts_name }} <> JS {{ en.ts_name }} (discriminated union on `tag`,
// payload under `inner`) —
// DECLARATION only; the definition lives in `{{ en.ts_name }}.conv.hpp` and is
// emitted once every struct in the cycle is complete (deferred so its body,
// which names the cycle partners, isn't instantiated before they're defined).
template <>
struct JSIConverter<margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}> final {
  using EnumT = margelo::nitro::{{ module.namespace }}::{{ en.ts_name }};
  static EnumT fromJSI(jsi::Runtime& runtime, const jsi::Value& arg);
  static jsi::Value toJSI(jsi::Runtime& runtime, const EnumT& arg);
  static bool canConvert(jsi::Runtime& runtime, const jsi::Value& value);
};

} // namespace margelo::nitro

// Bring in the cycle partners' full definitions, then the converter footers for
// every member of the cycle (each guarded so it fires exactly once — when all
// structs are complete). Including all members' footers from every member's
// header guarantees that whichever header the TU enters last completes every
// converter.
{%- for partner in en.cycle_partners %}
{%- if !partner.by_value %}
#include "{{ partner.header }}"
{%- endif %}
{%- endfor %}
#include "{{ en.ts_name }}.conv.hpp"
{%- for partner in en.cycle_partners %}
#include "{{ partner.conv_header }}"
{%- endfor %}

{%- else %}

namespace margelo::nitro {

{%- if en.flat %}

// C++ {{ en.ts_name }} <> JS {{ en.ts_name }} (string union)
template <>
struct JSIConverter<margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}> final {
  static inline margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}
  fromJSI(jsi::Runtime& runtime, const jsi::Value& arg) {
    std::string unionValue = JSIConverter<std::string>::fromJSI(runtime, arg);
    switch (hashString(unionValue.c_str(), unionValue.size())) {
{%- for variant in en.variants %}
      case hashString("{{ variant.ts_name }}"): return margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}::{{ variant.ts_name }};
{%- endfor %}
      default: [[unlikely]]
        throw std::invalid_argument("Cannot convert \"" + unionValue + "\" to enum {{ en.ts_name }} - invalid value!");
    }
  }
  static inline jsi::Value
  toJSI(jsi::Runtime& runtime, margelo::nitro::{{ module.namespace }}::{{ en.ts_name }} arg) {
    switch (arg) {
{%- for variant in en.variants %}
      case margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}::{{ variant.ts_name }}: return jsi::Value(runtime, ubrnInternedTag(runtime, "{{ variant.ts_name }}"));
{%- endfor %}
      default: [[unlikely]]
        throw std::invalid_argument("Cannot convert {{ en.ts_name }} to JS - invalid value: " + std::to_string(static_cast<int>(arg)) + "!");
    }
  }
  static inline bool canConvert(jsi::Runtime& runtime, const jsi::Value& value) {
    if (!value.isString()) {
      return false;
    }
    std::string unionValue = JSIConverter<std::string>::fromJSI(runtime, value);
    switch (hashString(unionValue.c_str(), unionValue.size())) {
{%- for variant in en.variants %}
      case hashString("{{ variant.ts_name }}"):
{%- endfor %}
        return true;
      default:
        return false;
    }
  }
};

{%- else %}

// C++ {{ en.ts_name }} <> JS {{ en.ts_name }} (discriminated union on `tag`,
// payload nested under `inner`)
template <>
struct JSIConverter<margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}> final {
  using EnumT = margelo::nitro::{{ module.namespace }}::{{ en.ts_name }};

  static inline EnumT fromJSI(jsi::Runtime& runtime, const jsi::Value& arg) {
    jsi::Object obj = arg.asObject(runtime);
    std::string __tag = JSIConverter<std::string>::fromJSI(
        runtime, obj.getProperty(runtime, PropNameIDCache::get(runtime, "tag")));
    switch (hashString(__tag.c_str(), __tag.size())) {
{%- for variant in en.variants %}
      case hashString("{{ variant.ts_name }}"): {
        margelo::nitro::{{ module.namespace }}::{{ variant.cxx_struct_name(en.ts_name) }} __v{};
{%- if !variant.fields.is_empty() %}
        jsi::Object __inner = obj.getProperty(runtime, PropNameIDCache::get(runtime, "inner")).asObject(runtime);
{%- if variant.has_nameless_fields %}
        jsi::Array __arr = __inner.asArray(runtime);
{%- for field in variant.fields %}
        __v.{{ field.cxx_name }} = JSIConverter<{{ field.ty.cxx_type() }}>::fromJSI(runtime, __arr.getValueAtIndex(runtime, {{ loop.index0 }}));
{%- endfor %}
{%- else %}
{%- for field in variant.fields %}
        __v.{{ field.cxx_name }} = JSIConverter<{{ field.ty.cxx_type() }}>::fromJSI(runtime, __inner.getProperty(runtime, PropNameIDCache::get(runtime, "{{ field.ts_name }}")));
{%- endfor %}
{%- endif %}
{%- endif %}
        return EnumT{EnumT::Variant{std::move(__v)}};
      }
{%- endfor %}
      default: [[unlikely]]
        throw std::invalid_argument("Cannot convert \"" + __tag + "\" to enum {{ en.ts_name }} - invalid tag!");
    }
  }

  static inline jsi::Value toJSI(jsi::Runtime& runtime, const EnumT& arg) {
    jsi::Object obj(runtime);
    switch (arg.variant.index()) {
{%- for variant in en.variants %}
      case {{ loop.index0 }}: {
        obj.setProperty(runtime, PropNameIDCache::get(runtime, "tag"), ubrnInternedTag(runtime, "{{ variant.ts_name }}"));
{%- if !variant.fields.is_empty() %}
        const auto& __v = std::get<{{ loop.index0 }}>(arg.variant);
{%- if variant.has_nameless_fields %}
        jsi::Array __inner(runtime, {{ variant.fields.len() }});
{%- for field in variant.fields %}
        __inner.setValueAtIndex(runtime, {{ loop.index0 }}, JSIConverter<{{ field.ty.cxx_type() }}>::toJSI(runtime, __v.{{ field.cxx_name }}));
{%- endfor %}
{%- else %}
        jsi::Object __inner(runtime);
{%- for field in variant.fields %}
        __inner.setProperty(runtime, PropNameIDCache::get(runtime, "{{ field.ts_name }}"), JSIConverter<{{ field.ty.cxx_type() }}>::toJSI(runtime, __v.{{ field.cxx_name }}));
{%- endfor %}
{%- endif %}
        obj.setProperty(runtime, PropNameIDCache::get(runtime, "inner"), __inner);
{%- endif %}
        break;
      }
{%- endfor %}
      default: [[unlikely]]
        throw std::invalid_argument("Cannot convert {{ en.ts_name }} to JS - invalid variant index!");
    }
    return obj;
  }

  static inline bool canConvert(jsi::Runtime& runtime, const jsi::Value& value) {
    if (!value.isObject()) {
      return false;
    }
    jsi::Object obj = value.getObject(runtime);
    const auto& tag_id = PropNameIDCache::get(runtime, "tag");
    if (!obj.hasProperty(runtime, tag_id)) {
      return false;
    }
    jsi::Value __tagValue = obj.getProperty(runtime, tag_id);
    if (!__tagValue.isString()) {
      return false;
    }
    std::string __tag = __tagValue.asString(runtime).utf8(runtime);
    switch (hashString(__tag.c_str(), __tag.size())) {
{%- for variant in en.variants %}
      case hashString("{{ variant.ts_name }}"):
{%- endfor %}
        return true;
      default:
        return false;
    }
  }
};

{%- endif %}

} // namespace margelo::nitro

{%- endif %}
