// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// Out-of-line `JSIConverter<{{ en.ts_name }}>` definition for a tagged enum in
// a header `#include` cycle. Included (idempotently, from every cycle member's
// header) *after* all the cycle's structs are complete; the guard below makes
// it expand exactly once — when every struct sentinel is set and this converter
// hasn't been defined yet. Out-of-lining the bodies keeps them from being
// instantiated before the partner types exist. No `#pragma once`: the guard is
// the include guard, and the footer must be re-evaluable on each inclusion so
// it can fire on whichever pass first sees all structs complete.

#if defined(UBRN_CYC_{{ module.namespace }}_{{ en.ts_name }}_STRUCT) \
{%- for partner in en.cycle_partners %}
  && defined({{ partner.struct_sentinel }}) \
{%- endfor %}
  && !defined(UBRN_CYC_{{ module.namespace }}_{{ en.ts_name }}_CONV)
#define UBRN_CYC_{{ module.namespace }}_{{ en.ts_name }}_CONV 1

#include <NitroModules/JSICache.hpp>

namespace margelo::nitro {

// Interned tag-value cache: the variant tag string ("VariantName") is a fixed
// ASCII literal, so its `jsi::String` can be allocated once per (runtime, tag)
// and reused, instead of building a fresh `jsi::String` on every `toJSI` node.
// Defined exactly once per translation unit via the include guard below; the
// per-enum CONV guard above is unique per enum, so multiple enum converters in
// one TU would otherwise each emit this definition.
#ifndef UBRN_INTERNED_TAG
#define UBRN_INTERNED_TAG 1
inline const jsi::Value& ubrnInternedTag(jsi::Runtime& runtime, const char* tag) {
  static std::unordered_map<jsi::Runtime*,
      std::unordered_map<const char*, BorrowingReference<jsi::Value>>> cache;
  auto& perRt = cache[&runtime];
  auto it = perRt.find(tag);
  if (it != perRt.end() && it->second != nullptr) return *it->second;
  auto shared = JSICache::getOrCreateCache(runtime)
                    .makeShared(jsi::Value(jsi::String::createFromAscii(runtime, tag)));
  auto [pos, _] = perRt.insert_or_assign(tag, std::move(shared));
  return *pos->second;
}
#endif

inline margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}
JSIConverter<margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}>::fromJSI(jsi::Runtime& runtime, const jsi::Value& arg) {
  using EnumT = margelo::nitro::{{ module.namespace }}::{{ en.ts_name }};
  jsi::Object obj = arg.asObject(runtime);
  const auto& tag_id = PropNameIDCache::get(runtime, "tag");
{%- if en.any_variant_has_fields() %}
  const auto& inner_id = PropNameIDCache::get(runtime, "inner");
{%- endif %}
  std::string __tag = JSIConverter<std::string>::fromJSI(
      runtime, obj.getProperty(runtime, tag_id));
  switch (hashString(__tag.c_str(), __tag.size())) {
{%- for variant in en.variants %}
    case hashString("{{ variant.ts_name }}"): {
      margelo::nitro::{{ module.namespace }}::{{ variant.cxx_struct_name(en.ts_name) }} __v{};
{%- if !variant.fields.is_empty() %}
      jsi::Object __inner = obj.getProperty(runtime, inner_id).asObject(runtime);
{%- if variant.has_nameless_fields %}
      jsi::Array __arr = __inner.asArray(runtime);
{%- for field in variant.fields %}
      __v.{{ field.cxx_name }} = JSIConverter<{{ field.ty.cxx_type() }}>::fromJSI(runtime, __arr.getValueAtIndex(runtime, {{ loop.index0 }}));
{%- endfor %}
{%- else %}
{%- for field in variant.fields %}
      __v.{{ field.cxx_name }} = JSIConverter<{{ field.ty.cxx_type() }}>::fromJSI(runtime, __inner.getProperty(runtime, PropNameIDCache::get(runtime, "{{ field.ts_name }}")));
{%- endfor %}
{%- endif %}
{%- endif %}
      return EnumT{EnumT::Variant{std::move(__v)}};
    }
{%- endfor %}
    default: [[unlikely]]
      throw std::invalid_argument("Cannot convert \"" + __tag + "\" to enum {{ en.ts_name }} - invalid tag!");
  }
}

inline jsi::Value
JSIConverter<margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}>::toJSI(jsi::Runtime& runtime, const margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}& arg) {
  jsi::Object obj(runtime);
  const auto& tag_id = PropNameIDCache::get(runtime, "tag");
{%- if en.any_variant_has_fields() %}
  const auto& inner_id = PropNameIDCache::get(runtime, "inner");
{%- endif %}
  switch (arg.variant.index()) {
{%- for variant in en.variants %}
    case {{ loop.index0 }}: {
      obj.setProperty(runtime, tag_id, ubrnInternedTag(runtime, "{{ variant.ts_name }}"));
{%- if !variant.fields.is_empty() %}
      const auto& __v = std::get<{{ loop.index0 }}>(arg.variant);
{%- if variant.has_nameless_fields %}
      jsi::Array __inner(runtime, {{ variant.fields.len() }});
{%- for field in variant.fields %}
      __inner.setValueAtIndex(runtime, {{ loop.index0 }}, JSIConverter<{{ field.ty.cxx_type() }}>::toJSI(runtime, __v.{{ field.cxx_name }}));
{%- endfor %}
{%- else %}
      jsi::Object __inner(runtime);
{%- for field in variant.fields %}
      __inner.setProperty(runtime, PropNameIDCache::get(runtime, "{{ field.ts_name }}"), JSIConverter<{{ field.ty.cxx_type() }}>::toJSI(runtime, __v.{{ field.cxx_name }}));
{%- endfor %}
{%- endif %}
      obj.setProperty(runtime, inner_id, __inner);
{%- endif %}
      break;
    }
{%- endfor %}
    default: [[unlikely]]
      throw std::invalid_argument("Cannot convert {{ en.ts_name }} to JS - invalid variant index!");
  }
  return obj;
}

inline bool
JSIConverter<margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}>::canConvert(jsi::Runtime& runtime, const jsi::Value& value) {
  if (!value.isObject()) {
    return false;
  }
  jsi::Object obj = value.getObject(runtime);
  const auto& tag_id = PropNameIDCache::get(runtime, "tag");
  if (!obj.hasProperty(runtime, tag_id)) {
    return false;
  }
  jsi::Value __tagValue = obj.getProperty(runtime, tag_id);
  if (!__tagValue.isString()) {
    return false;
  }
  std::string __tag = __tagValue.asString(runtime).utf8(runtime);
  switch (hashString(__tag.c_str(), __tag.size())) {
{%- for variant in en.variants %}
    case hashString("{{ variant.ts_name }}"):
{%- endfor %}
      return true;
    default:
      return false;
  }
}

} // namespace margelo::nitro

#endif
