// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// Out-of-line `JSIConverter<{{ en.ts_name }}>` definition for a tagged enum in
// a header `#include` cycle. Included (idempotently, from every cycle member's
// header) *after* all the cycle's structs are complete; the guard below makes
// it expand exactly once — when every struct sentinel is set and this converter
// hasn't been defined yet. Out-of-lining the bodies keeps them from being
// instantiated before the partner types exist. No `#pragma once`: the guard is
// the include guard, and the footer must be re-evaluable on each inclusion so
// it can fire on whichever pass first sees all structs complete.

#if defined(UBRN_CYC_{{ module.namespace }}_{{ en.ts_name }}_STRUCT) \
{%- for partner in en.cycle_partners %}
  && defined({{ partner.struct_sentinel }}) \
{%- endfor %}
  && !defined(UBRN_CYC_{{ module.namespace }}_{{ en.ts_name }}_CONV)
#define UBRN_CYC_{{ module.namespace }}_{{ en.ts_name }}_CONV 1

namespace margelo::nitro {

inline margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}
JSIConverter<margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}>::fromJSI(jsi::Runtime& runtime, const jsi::Value& arg) {
  using EnumT = margelo::nitro::{{ module.namespace }}::{{ en.ts_name }};
  jsi::Object obj = arg.asObject(runtime);
  std::string __tag = JSIConverter<std::string>::fromJSI(
      runtime, obj.getProperty(runtime, PropNameIDCache::get(runtime, "type")));
  switch (hashString(__tag.c_str(), __tag.size())) {
{%- for variant in en.variants %}
    case hashString("{{ variant.tag }}"): {
      margelo::nitro::{{ module.namespace }}::{{ variant.cxx_struct_name(en.ts_name) }} __v{};
{%- for field in variant.fields %}
      __v.{{ field.cxx_name }} = JSIConverter<{{ field.ty.cxx_type() }}>::fromJSI(runtime, obj.getProperty(runtime, PropNameIDCache::get(runtime, "{{ field.ts_name }}")));
{%- endfor %}
      return EnumT{EnumT::Variant{std::move(__v)}};
    }
{%- endfor %}
    default: [[unlikely]]
      throw std::invalid_argument("Cannot convert \"" + __tag + "\" to enum {{ en.ts_name }} - invalid tag!");
  }
}

inline jsi::Value
JSIConverter<margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}>::toJSI(jsi::Runtime& runtime, const margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}& arg) {
  jsi::Object obj(runtime);
  switch (arg.variant.index()) {
{%- for variant in en.variants %}
    case {{ loop.index0 }}: {
      obj.setProperty(runtime, PropNameIDCache::get(runtime, "type"), JSIConverter<std::string>::toJSI(runtime, "{{ variant.tag }}"));
{%- if !variant.fields.is_empty() %}
      const auto& __v = std::get<{{ loop.index0 }}>(arg.variant);
{%- for field in variant.fields %}
      obj.setProperty(runtime, PropNameIDCache::get(runtime, "{{ field.ts_name }}"), JSIConverter<{{ field.ty.cxx_type() }}>::toJSI(runtime, __v.{{ field.cxx_name }}));
{%- endfor %}
{%- endif %}
      break;
    }
{%- endfor %}
    default: [[unlikely]]
      throw std::invalid_argument("Cannot convert {{ en.ts_name }} to JS - invalid variant index!");
  }
  return obj;
}

inline bool
JSIConverter<margelo::nitro::{{ module.namespace }}::{{ en.ts_name }}>::canConvert(jsi::Runtime& runtime, const jsi::Value& value) {
  if (!value.isObject()) {
    return false;
  }
  jsi::Object obj = value.getObject(runtime);
  if (!obj.hasProperty(runtime, PropNameIDCache::get(runtime, "type"))) {
    return false;
  }
  jsi::Value __type = obj.getProperty(runtime, PropNameIDCache::get(runtime, "type"));
  if (!__type.isString()) {
    return false;
  }
  std::string __tag = __type.asString(runtime).utf8(runtime);
  switch (hashString(__tag.c_str(), __tag.size())) {
{%- for variant in en.variants %}
    case hashString("{{ variant.tag }}"):
{%- endfor %}
      return true;
    default:
      return false;
  }
}

} // namespace margelo::nitro

#endif
