// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// HybridObject impl for uniffi interface `{{ iface.ts_name }}` in crate
// `{{ module.crate_name }}`.
#pragma once

#include <NitroModules/HybridObject.hpp>
#include <NitroModules/Promise.hpp>
#include <NitroUniffi.hpp>
#include <nitro-uniffi/jsi_converter_ints.hpp>

#include <memory>
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>

// Per-type headers for every record / enum / interface this interface's
// methods take or return.
{%- for header in iface.dependency_headers() %}
#include "{{ header }}"
{%- endfor %}

extern "C" {
void {{ iface.free_symbol }}(uint64_t handle, UniffiRustCallStatus* status);
{%- if let Some(ctor) = iface.primary_constructor() %}
uint64_t {{ ctor.uniffi_symbol }}(UniffiRustCallStatus* status);
{%- endif %}
}

namespace margelo::nitro::{{ module.namespace }} {

class {{ iface.cxx_class }} : public ::margelo::nitro::HybridObject {
public:
  static constexpr auto TAG = "{{ iface.ts_name }}";

{%- if let Some(ctor) = iface.primary_constructor() %}
  // Default constructor — runs the uniffi `{{ ctor.uniffi_symbol }}`
  // constructor so `NitroModules.createHybridObject('{{ iface.ts_name }}')`
  // (and the JS `new {{ iface.ts_name }}()` shim) yield a live Rust object.
  {{ iface.cxx_class }}() : HybridObject(TAG), handle_(make_handle()) {}
{%- else %}
  // Default constructor — yields a null-handle instance. This interface's
  // construction needs arguments (or is fallible/async), which Nitro's
  // argless `createHybridObject` factory can't drive; live instances are
  // vended from method/function returns instead.
  {{ iface.cxx_class }}() : HybridObject(TAG), handle_() {}
{%- endif %}

  // Borrowed-handle construction — used internally by the namespace API
  // when invoking a uniffi constructor or interface-returning method.
  explicit {{ iface.cxx_class }}(uint64_t raw_handle)
      : HybridObject(TAG), handle_(raw_handle) {}

  /// Public accessor for the raw uniffi handle. Used internally where a
  /// borrowed (non-consuming) view of the handle is needed.
  uint64_t raw_handle() const { return handle_.raw(); }

  /// Clone the underlying uniffi Arc handle (bumps the Rust-side strong
  /// count) and return the fresh handle. uniffi method / function calls and
  /// argument lowering *consume* the handle they are handed — the scaffolding
  /// does `Arc::from_raw` and drops it on return — so every place that passes
  /// this object's handle to Rust must hand over a clone, or the first such
  /// call drops our retained reference and frees the object out from under us.
  uint64_t clone_handle() const;

{%- for method in iface.methods %}
  {{ method.cxx_return_signature() }} {{ method.cxx_name }}(
{%- for arg in method.args -%}
    {{ arg.ty.cxx_type() }} {{ arg.ts_name }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  );
{%- endfor %}

protected:
  void loadHybridMethods() override;

private:
{%- if iface.primary_constructor().is_some() %}
  // Drives the uniffi constructor (defined in the .cpp, where the
  // namespace buffer-free symbol is in scope), surfacing any
  // `RustCallStatus` error as a C++ exception that Nitro relays to JS.
  static uint64_t make_handle();
{%- endif %}
  ubrn::nitro::UniffiObjectHandle<&{{ iface.free_symbol }}> handle_;
};

} // namespace margelo::nitro::{{ module.namespace }}
