// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// HybridObject impl for uniffi interface `{{ iface.ts_name }}` in crate
// `{{ module.crate_name }}`.
#include "{{ iface.cxx_class }}.hpp"
#include "{{ module.codecs_header_filename() }}"

#include <NitroModules/Promise.hpp>

extern "C" {
RustBuffer {{ module.rustbuffer_alloc }}(uint64_t size, UniffiRustCallStatus* status);
void {{ module.rustbuffer_free }}(RustBuffer buf, UniffiRustCallStatus* status);
RustBuffer {{ module.rustbuffer_reserve }}(RustBuffer buf, uint64_t add, UniffiRustCallStatus* status);
uint64_t {{ iface.clone_symbol }}(uint64_t handle, UniffiRustCallStatus* status);
{%- if let Some(ctor) = iface.primary_constructor() %}
uint64_t {{ ctor.uniffi_symbol }}(UniffiRustCallStatus* status);
{%- endif %}

{%- for method in iface.methods %}
{%- if method.is_async %}
uint64_t {{ method.uniffi_symbol }}(
    uint64_t self_handle{% if !method.args.is_empty() %},{% endif %}
{%- for arg in method.args -%}
    {{ arg.ty.c_type() }} {{ arg.ts_name }}_lowered{% if !loop.last %}, {% endif %}
{%- endfor -%}
);
{%- if let Some(ad) = method.async_data %}
void {{ ad.poll_symbol }}(uint64_t handle, void (*cb)(uint64_t, int8_t), uint64_t cb_data);
void {{ ad.free_symbol }}(uint64_t handle);
{{ method.return_kind.c_type() }} {{ ad.complete_symbol }}(uint64_t handle, UniffiRustCallStatus* status);
{%- endif %}
{%- else %}
{{ method.return_kind.c_type() }} {{ method.uniffi_symbol }}(
    uint64_t self_handle,
{%- for arg in method.args -%}
    {{ arg.ty.c_type() }} {{ arg.ts_name }}_lowered,
{%- endfor -%}
    UniffiRustCallStatus* status
);
{%- endif %}
{%- endfor %}
}

namespace margelo::nitro::{{ module.namespace }} {

namespace {
inline void free_status_buffer(RustBuffer buf) noexcept {
  UniffiRustCallStatus s{};
  {{ module.rustbuffer_free }}(buf, &s);
}
} // namespace

uint64_t {{ iface.cxx_class }}::clone_handle() const {
  // A zero handle means this is a default-constructed shell (an interface
  // whose construction needs arguments, reached via the argless JS shim).
  // Cloning it would call `Arc::increment_strong_count(nullptr)` on the Rust
  // side — a null deref, not a clean error — so fail loudly instead.
  if (handle_.raw() == 0) {
    throw std::runtime_error(
        "{{ iface.ts_name }}: method/argument use of an uninitialized handle "
        "(this interface cannot be constructed with `new {{ iface.ts_name }}()`)");
  }
  auto __status = ubrn::nitro::make_status();
  uint64_t __cloned = {{ iface.clone_symbol }}(handle_.raw(), &__status);
  ubrn::nitro::check_status(__status, free_status_buffer);
  return __cloned;
}

{%- if let Some(ctor) = iface.primary_constructor() %}
uint64_t {{ iface.cxx_class }}::make_handle() {
  auto __status = ubrn::nitro::make_status();
  uint64_t __raw = {{ ctor.uniffi_symbol }}(&__status);
  ubrn::nitro::check_status(__status, free_status_buffer);
  return __raw;
}
{%- endif %}

void {{ iface.cxx_class }}::loadHybridMethods() {
  HybridObject::loadHybridMethods();
  registerHybrids(this, [](Prototype& prototype) {
{%- for method in iface.methods %}
    prototype.registerHybridMethod("{{ method.ts_name }}", &{{ iface.cxx_class }}::{{ method.cxx_name }});
{%- endfor %}
  });
}

{%- for method in iface.methods %}
{{ method.cxx_return_signature() }} {{ iface.cxx_class }}::{{ method.cxx_name }}(
{%- for arg in method.args -%}
    {{ arg.ty.cxx_type() }} {{ arg.ts_name }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
) {
{%- if method.is_async %}
{%- if let Some(ad) = method.async_data %}
{%- for arg in method.args %}
  auto {{ arg.ts_name }}_lowered = {{ arg.ty.lower_expr(arg.ts_name, module.rustbuffer_alloc, module.rustbuffer_reserve) }};
{%- endfor %}
  uint64_t __handle = {{ method.uniffi_symbol }}(clone_handle(){% if !method.args.is_empty() %},{% endif %}
{%- for arg in method.args -%}
    {{ arg.ts_name }}_lowered{% if !loop.last %}, {% endif %}
{%- endfor -%}
  );
  return ::margelo::nitro::Promise<{{ method.return_kind.cxx_type() }}>::async(
      [__handle]() -> {{ method.return_kind.cxx_type() }} {
        ::ubrn::nitro::drive_rust_future(
            __handle,
            &{{ ad.poll_symbol }});
        auto __status = ::ubrn::nitro::make_status();
{%- match method.return_kind %}
{%- when crate::bindings::gen_nitro::model::ReturnKind::Void %}
        {{ ad.complete_symbol }}(__handle, &__status);
        {{ ad.free_symbol }}(__handle);
{%- if let Some(throws) = method.throws %}
        try {
          ::ubrn::nitro::check_status(__status, free_status_buffer);
        } catch (::ubrn::nitro::UniffiTypedError& __typed) {
          // Decode borrows the buffer; __typed frees it on scope exit (even
          // if the decoder itself throws).
          auto __decoded = {{ throws.lift_fn() }}(__typed.buffer());
          throw __decoded;
        }
{%- else %}
        ::ubrn::nitro::check_status(__status, free_status_buffer);
{%- endif %}
        return;
{%- when crate::bindings::gen_nitro::model::ReturnKind::Value with (ret_ty) %}
        auto __raw = {{ ad.complete_symbol }}(__handle, &__status);
        {{ ad.free_symbol }}(__handle);
{%- if let Some(throws) = method.throws %}
        try {
          ::ubrn::nitro::check_status(__status, free_status_buffer);
        } catch (::ubrn::nitro::UniffiTypedError& __typed) {
          // Decode borrows the buffer; __typed frees it on scope exit (even
          // if the decoder itself throws).
          auto __decoded = {{ throws.lift_fn() }}(__typed.buffer());
          throw __decoded;
        }
{%- else %}
        ::ubrn::nitro::check_status(__status, free_status_buffer);
{%- endif %}
{%- if method.return_kind.returns_owned_rustbuffer() %}
{%- if ret_ty.lift_consumes_buffer() %}
        return {{ ret_ty.lift_owning_expr("__raw", module.rustbuffer_free) }};
{%- else %}
        ::ubrn::nitro::RustBufferGuard __raw_guard{__raw, &free_status_buffer};
        return {{ ret_ty.lift_expr("__raw") }};
{%- endif %}
{%- else %}
        return {{ ret_ty.lift_expr("__raw") }};
{%- endif %}
{%- endmatch %}
      });
{%- endif %}
{%- else %}
  auto __status = ubrn::nitro::make_status();
{%- for arg in method.args %}
  auto {{ arg.ts_name }}_lowered = {{ arg.ty.lower_expr(arg.ts_name, module.rustbuffer_alloc, module.rustbuffer_reserve) }};
{%- endfor %}
{%- match method.return_kind %}
{%- when crate::bindings::gen_nitro::model::ReturnKind::Void %}
  {{ method.uniffi_symbol }}(clone_handle(),
{%- for arg in method.args -%}
    {{ arg.ts_name }}_lowered,
{%- endfor -%}
    &__status);
{%- if let Some(throws) = method.throws %}
  try {
    ubrn::nitro::check_status(__status, free_status_buffer);
  } catch (ubrn::nitro::UniffiTypedError& __typed) {
    // Decode borrows the buffer; __typed frees it on scope exit (even if
    // the decoder itself throws).
    auto __decoded = {{ throws.lift_fn() }}(__typed.buffer());
    throw __decoded;
  }
{%- else %}
  ubrn::nitro::check_status(__status, free_status_buffer);
{%- endif %}
{%- when crate::bindings::gen_nitro::model::ReturnKind::Value with (ret_ty) %}
  auto __raw = {{ method.uniffi_symbol }}(clone_handle(),
{%- for arg in method.args -%}
    {{ arg.ts_name }}_lowered,
{%- endfor -%}
    &__status);
{%- if let Some(throws) = method.throws %}
  try {
    ubrn::nitro::check_status(__status, free_status_buffer);
  } catch (ubrn::nitro::UniffiTypedError& __typed) {
    // Decode borrows the buffer; __typed frees it on scope exit (even if
    // the decoder itself throws).
    auto __decoded = {{ throws.lift_fn() }}(__typed.buffer());
    throw __decoded;
  }
{%- else %}
  ubrn::nitro::check_status(__status, free_status_buffer);
{%- endif %}
{%- if method.return_kind.returns_owned_rustbuffer() %}
{%- if ret_ty.lift_consumes_buffer() %}
  // Zero-copy: hand the Rust-owned buffer's payload straight to JS as the
  // ArrayBuffer backing store; freed via the namespace hook on JS GC.
  return {{ ret_ty.lift_owning_expr("__raw", module.rustbuffer_free) }};
{%- else %}
  // RAII: free the Rust-owned return buffer on scope exit, so a throwing
  // lift (malformed payload / OOM) can't leak it.
  ubrn::nitro::RustBufferGuard __raw_guard{__raw, &free_status_buffer};
  return {{ ret_ty.lift_expr("__raw") }};
{%- endif %}
{%- else %}
  return {{ ret_ty.lift_expr("__raw") }};
{%- endif %}
{%- endmatch %}
{%- endif %}
}
{%- endfor %}

} // namespace margelo::nitro::{{ module.namespace }}
