// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// HybridObject impl for uniffi interface `{{ iface.ts_name }}` in crate
// `{{ module.crate_name }}`.
#pragma once

#include <NitroModules/HybridObject.hpp>
#include <NitroUniffi.hpp>

extern "C" {
void {{ iface.free_symbol }}(uint64_t handle, UniffiRustCallStatus* status);
}

namespace margelo::nitro::{{ module.namespace }} {

class {{ iface.cxx_class }} : public ::margelo::nitro::HybridObject {
public:
  static constexpr auto TAG = "{{ iface.ts_name }}";

  // Default constructor — required for Nitrogen's default-constructible
  // registry factory. Real instances should be vended via the namespace
  // API HybridObject's constructor methods rather than this path.
  {{ iface.cxx_class }}() : HybridObject(TAG), handle_() {}

  // Borrowed-handle construction — used internally by the namespace API
  // when invoking a uniffi constructor or interface-returning method.
  explicit {{ iface.cxx_class }}(uint64_t raw_handle)
      : HybridObject(TAG), handle_(raw_handle) {}

  /// Public accessor for the raw uniffi handle. Used by other generated
  /// HybridObject impls' lowering expressions when this interface is
  /// passed as an argument.
  uint64_t raw_handle() const { return handle_.raw(); }

{%- for method in iface.methods %}
  {{ method.cxx_return_signature() }} {{ method.cxx_name }}(
{%- for arg in method.args -%}
    {{ arg.ty.cxx_type() }} {{ arg.ts_name }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  );
{%- endfor %}

protected:
  void loadHybridMethods() override;

private:
  ubrn::nitro::UniffiObjectHandle<&{{ iface.free_symbol }}> handle_;
};

} // namespace margelo::nitro::{{ module.namespace }}
