// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// HybridObject impl for uniffi interface `{{ iface.ts_name }}` in crate
// `{{ module.crate_name }}`.
#include "{{ iface.cxx_class }}.hpp"
#include "{{ module.codecs_header_filename() }}"
// Full definitions of interface types this interface constructs / calls
// (forward-declared in the .hpp, included here where the complete type is
// needed for `make_shared` and method dispatch).
{%- for header in iface.interface_dependency_headers() %}
#include "{{ header }}"
{%- endfor %}

#include <NitroModules/Promise.hpp>

extern "C" {
RustBuffer {{ module.rustbuffer_alloc }}(uint64_t size, UniffiRustCallStatus* status);
void {{ module.rustbuffer_free }}(RustBuffer buf, UniffiRustCallStatus* status);
RustBuffer {{ module.rustbuffer_reserve }}(RustBuffer buf, uint64_t add, UniffiRustCallStatus* status);
uint64_t {{ iface.clone_symbol }}(uint64_t handle, UniffiRustCallStatus* status);
{%- if let Some(ctor) = iface.primary_constructor() %}
uint64_t {{ ctor.uniffi_symbol }}(UniffiRustCallStatus* status);
{%- endif %}

{%- for method in iface.methods %}
{%- if method.is_async %}
uint64_t {{ method.uniffi_symbol }}(
    uint64_t self_handle{% if !method.args.is_empty() %},{% endif %}
{%- for arg in method.args -%}
    {{ arg.ty.c_type() }} {{ arg.ts_name }}_lowered{% if !loop.last %}, {% endif %}
{%- endfor -%}
);
{%- if let Some(ad) = method.async_data %}
void {{ ad.poll_symbol }}(uint64_t handle, void (*cb)(uint64_t, int8_t), uint64_t cb_data);
void {{ ad.free_symbol }}(uint64_t handle);
// uniffi async cancel — one arg (the future handle), void return, no status.
void {{ ad.cancel_symbol }}(uint64_t handle);
{{ method.return_kind.c_type() }} {{ ad.complete_symbol }}(uint64_t handle, UniffiRustCallStatus* status);
{%- endif %}
{%- else %}
{{ method.return_kind.c_type() }} {{ method.uniffi_symbol }}(
    uint64_t self_handle,
{%- for arg in method.args -%}
    {{ arg.ty.c_type() }} {{ arg.ts_name }}_lowered,
{%- endfor -%}
    UniffiRustCallStatus* status
);
{%- endif %}
{%- endfor %}
{%- for tf in iface.uniffi_trait_functions() %}
// uniffi object-trait FFI symbol (`…_uniffi_trait_*`). Display/Debug return a
// RustBuffer (UTF-8 String); Hash a u64; Eq a bool (i8); Ord an i8. Eq/Ord take
// the cloned `other` handle as their one arg.
{{ tf.return_kind.c_type() }} {{ tf.uniffi_symbol }}(
    uint64_t self_handle,
{%- for arg in tf.args -%}
    {{ arg.ty.c_type() }} {{ arg.ts_name }}_lowered,
{%- endfor -%}
    UniffiRustCallStatus* status
);
{%- endfor %}
}

namespace margelo::nitro::{{ module.namespace }} {

uint64_t {{ iface.cxx_class }}::clone_handle() const {
  // A zero handle means this is a default-constructed shell (an interface
  // whose construction needs arguments, reached via the argless JS shim).
  // Cloning it would call `Arc::increment_strong_count(nullptr)` on the Rust
  // side — a null deref, not a clean error — so fail loudly instead.
  if (handle_.raw() == 0) {
    throw std::runtime_error(
        "{{ iface.ts_name }}: method/argument use of an uninitialized handle "
        "(this interface cannot be constructed with `new {{ iface.ts_name }}()`)");
  }
  auto __status = ubrn::nitro::make_status();
  uint64_t __cloned = {{ iface.clone_symbol }}(handle_.raw(), &__status);
  ubrn::nitro::check_status(__status, free_status_buffer);
  return __cloned;
}

{%- if let Some(ctor) = iface.primary_constructor() %}
uint64_t {{ iface.cxx_class }}::make_handle() {
  auto __status = ubrn::nitro::make_status();
  uint64_t __raw = {{ ctor.uniffi_symbol }}(&__status);
  ubrn::nitro::check_status(__status, free_status_buffer);
  return __raw;
}
{%- endif %}

void {{ iface.cxx_class }}::loadHybridMethods() {
  HybridObject::loadHybridMethods();
  registerHybrids(this, [](Prototype& prototype) {
{%- for method in iface.methods %}
    prototype.registerHybridMethod("{{ method.ts_name }}", &{{ iface.cxx_class }}::{{ method.cxx_name }});
{%- endfor %}
{%- if iface.has_async_methods() %}
    // Non-spec async-cancellation hooks (see the `.hpp` declaration + the
    // `.ts` wrapper's `__uniffiBeginAbortable` / `__uniffiAbort` usage).
    prototype.registerHybridMethod("__uniffiBeginAbortable", &{{ iface.cxx_class }}::__uniffiBeginAbortable);
    prototype.registerHybridMethod("__uniffiAbort", &{{ iface.cxx_class }}::__uniffiAbort);
{%- endif %}
{%- for tm in iface.uniffi_traits %}
{%- match tm %}
{%- when crate::bindings::gen_nitro::model::NitroUniffiTrait::Display { method } %}
    // `toString` / `equals` are base `HybridObject` virtuals, but Nitro
    // registers each prototype's methods on the *derived* prototype only and the
    // base's registration lands on the `HybridObject` prototype — so the derived
    // JS object does not see `toString`/`equals` unless we register them on THIS
    // prototype too. Registering here is safe: the duplicate-name guard is
    // per-prototype (`Prototype::_methods`), and this prototype does not already
    // carry `toString` (only the base does). We register the *derived override*
    // pointer, so virtual dispatch is moot — it IS our override.
    prototype.registerHybridMethod("toString", &{{ iface.cxx_class }}::toString);
{%- when crate::bindings::gen_nitro::model::NitroUniffiTrait::Debug { method } %}
    prototype.registerHybridMethod("toDebugString", &{{ iface.cxx_class }}::toDebugString);
{%- if !iface.has_display_trait() %}
    // No `Display` impl — `toString` aliases Debug; register it on this
    // prototype (same per-prototype-safe reasoning as the Display arm).
    prototype.registerHybridMethod("toString", &{{ iface.cxx_class }}::toString);
{%- endif %}
{%- when crate::bindings::gen_nitro::model::NitroUniffiTrait::Eq { method } %}
    // See the `Display` arm: `equals` must be registered on this derived
    // prototype to be visible on the JS object.
    prototype.registerHybridMethod("equals", &{{ iface.cxx_class }}::equals);
{%- when crate::bindings::gen_nitro::model::NitroUniffiTrait::Hash { method } %}
    prototype.registerHybridMethod("hashCode", &{{ iface.cxx_class }}::hashCode);
{%- when crate::bindings::gen_nitro::model::NitroUniffiTrait::Ord { method } %}
    prototype.registerHybridMethod("compareTo", &{{ iface.cxx_class }}::compareTo);
{%- endmatch %}
{%- endfor %}
  });
}

{%- if iface.has_async_methods() %}
double {{ iface.cxx_class }}::__uniffiBeginAbortable() {
  return static_cast<double>(::ubrn::nitro::begin_abortable_future());
}

void {{ iface.cxx_class }}::__uniffiAbort(double token) {
  ::ubrn::nitro::abort_rust_future(static_cast<uint64_t>(token));
}
{%- endif %}

{%- for tm in iface.uniffi_traits %}
{%- match tm %}
{%- when crate::bindings::gen_nitro::model::NitroUniffiTrait::Display { method } %}
std::string {{ iface.cxx_class }}::toString() {
  // uniffi `Display` → a String-returning trait call on the cloned receiver
  // handle. Infallible; the Rust-owned return buffer is freed by the RAII guard.
  auto __status = ubrn::nitro::make_status();
  ubrn::nitro::UniffiObjectHandle<&{{ iface.free_symbol }}> __self_guard{clone_handle()};
  auto __raw = {{ method.uniffi_symbol }}(__self_guard.take(), &__status);
  ubrn::nitro::check_status(__status, free_status_buffer);
  ubrn::nitro::RustBufferGuard __raw_guard{__raw, &free_status_buffer};
  return ubrn::nitro::lift_string(__raw);
}
{%- when crate::bindings::gen_nitro::model::NitroUniffiTrait::Debug { method } %}
std::string {{ iface.cxx_class }}::toDebugString() {
  // uniffi `Debug` → a String-returning trait call (see `toString`).
  auto __status = ubrn::nitro::make_status();
  ubrn::nitro::UniffiObjectHandle<&{{ iface.free_symbol }}> __self_guard{clone_handle()};
  auto __raw = {{ method.uniffi_symbol }}(__self_guard.take(), &__status);
  ubrn::nitro::check_status(__status, free_status_buffer);
  ubrn::nitro::RustBufferGuard __raw_guard{__raw, &free_status_buffer};
  return ubrn::nitro::lift_string(__raw);
}
{%- if !iface.has_display_trait() %}
std::string {{ iface.cxx_class }}::toString() {
  // No `Display` impl — defer to Debug (mirrors the JSI oracle).
  return toDebugString();
}
{%- endif %}
{%- when crate::bindings::gen_nitro::model::NitroUniffiTrait::Eq { method } %}
bool {{ iface.cxx_class }}::equals(const std::shared_ptr<::margelo::nitro::HybridObject>& other) {
  // uniffi `Eq`. The base virtual's param is the BASE type; downcast to the
  // concrete `{{ iface.cxx_class }}` (only it has `clone_handle()`), returning
  // false on a type mismatch — a different concrete Hybrid is simply not equal.
  auto __other = std::dynamic_pointer_cast<{{ iface.cxx_class }}>(other);
  if (!__other) {
    return false;
  }
  // Lower both handles (clone — uniffi consumes each), parked in move-only
  // guards so a throw frees the already-cloned handle, then call eq + lift bool.
  auto __status = ubrn::nitro::make_status();
  ubrn::nitro::UniffiObjectHandle<&{{ iface.free_symbol }}> __self_guard{clone_handle()};
  ubrn::nitro::UniffiObjectHandle<&{{ iface.free_symbol }}> __other_guard{__other->clone_handle()};
  auto __raw = {{ method.uniffi_symbol }}(__self_guard.take(), __other_guard.take(), &__status);
  ubrn::nitro::check_status(__status, free_status_buffer);
  return ubrn::nitro::lift_bool(__raw);
}
{%- when crate::bindings::gen_nitro::model::NitroUniffiTrait::Hash { method } %}
{{ method.cxx_return_signature() }} {{ iface.cxx_class }}::hashCode() {
  // uniffi `Hash` → u64 on the cloned receiver. Infallible scalar return.
  auto __status = ubrn::nitro::make_status();
  ubrn::nitro::UniffiObjectHandle<&{{ iface.free_symbol }}> __self_guard{clone_handle()};
  auto __raw = {{ method.uniffi_symbol }}(__self_guard.take(), &__status);
  ubrn::nitro::check_status(__status, free_status_buffer);
  return __raw;
}
{%- when crate::bindings::gen_nitro::model::NitroUniffiTrait::Ord { method } %}
{{ method.cxx_return_signature() }} {{ iface.cxx_class }}::compareTo(const std::shared_ptr<{{ iface.cxx_class }}>& other) {
  // uniffi `Ord` → i8 (-1/0/1) comparing the cloned receiver + cloned `other`.
  auto __status = ubrn::nitro::make_status();
  ubrn::nitro::UniffiObjectHandle<&{{ iface.free_symbol }}> __self_guard{clone_handle()};
  ubrn::nitro::UniffiObjectHandle<&{{ iface.free_symbol }}> __other_guard{other->clone_handle()};
  auto __raw = {{ method.uniffi_symbol }}(__self_guard.take(), __other_guard.take(), &__status);
  ubrn::nitro::check_status(__status, free_status_buffer);
  return __raw;
}
{%- endmatch %}
{%- endfor %}

{%- for method in iface.methods %}
{{ method.cxx_return_signature() }} {{ iface.cxx_class }}::{{ method.cxx_name }}(
{%- for arg in method.args -%}
    {{ arg.ty.cxx_type() }} {{ arg.ts_name }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
) {
{%- if method.is_async %}
{%- if let Some(ad) = method.async_data %}
  // Exception-safe lowering (audit bug #24) — the cloned receiver handle, owning
  // RustBuffer args, and interface / callback handle args are parked in move-only
  // guards and `.take()`-d into the eager future kick-off only after every
  // lowering succeeds, so a throw mid-prologue frees the already-built
  // handle/buffers instead of leaking them.
  ubrn::nitro::UniffiObjectHandle<&{{ iface.free_symbol }}> __self_guard{clone_handle()};
{%- for arg in method.args %}
  {{ arg.lower_guard_stmt(module.namespace, module.rustbuffer_alloc, module.rustbuffer_reserve) }}
{%- endfor %}
  uint64_t __handle = {{ method.uniffi_symbol }}(__self_guard.take(){% if !method.args.is_empty() %},{% endif %}
{%- for arg in method.args -%}
    {{ arg.pass_expr() }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  );
{%- match method.return_kind %}
{%- when crate::bindings::gen_nitro::model::ReturnKind::Void %}
  return ::ubrn::nitro::drive_rust_future_async_void(
      __handle, &{{ ad.poll_symbol }}, &{{ ad.free_symbol }},
      [__handle]() {
        auto __status = ::ubrn::nitro::make_status();
        {{ ad.complete_symbol }}(__handle, &__status);
{%- if let Some(throws) = method.throws %}
        try {
          ::ubrn::nitro::check_status(__status, free_status_buffer);
        } catch (::ubrn::nitro::UniffiTypedError& __typed) {
          throw {{ throws.lift_fn(module.namespace) }}(__typed.buffer());
        }
{%- else %}
        ::ubrn::nitro::check_status(__status, free_status_buffer);
{%- endif %}
      },
      &{{ ad.cancel_symbol }});
{%- when crate::bindings::gen_nitro::model::ReturnKind::Value with (ret_ty) %}
  return ::ubrn::nitro::drive_rust_future_async<{{ ret_ty.cxx_type() }}>(
      __handle, &{{ ad.poll_symbol }}, &{{ ad.free_symbol }},
      [__handle]() -> {{ ret_ty.cxx_type() }} {
        auto __status = ::ubrn::nitro::make_status();
        auto __raw = {{ ad.complete_symbol }}(__handle, &__status);
{%- if let Some(throws) = method.throws %}
        try {
          ::ubrn::nitro::check_status(__status, free_status_buffer);
        } catch (::ubrn::nitro::UniffiTypedError& __typed) {
          throw {{ throws.lift_fn(module.namespace) }}(__typed.buffer());
        }
{%- else %}
        ::ubrn::nitro::check_status(__status, free_status_buffer);
{%- endif %}
{%- if method.return_kind.returns_owned_rustbuffer() %}
{%- if ret_ty.lift_consumes_buffer() %}
        return {{ ret_ty.lift_owning_expr("__raw", module.namespace, module.rustbuffer_free) }};
{%- else %}
        ::ubrn::nitro::RustBufferGuard __raw_guard{__raw, &free_status_buffer};
        return {{ ret_ty.lift_expr("__raw", module.namespace) }};
{%- endif %}
{%- else %}
        return {{ ret_ty.lift_expr("__raw", module.namespace) }};
{%- endif %}
      },
      &{{ ad.cancel_symbol }});
{%- endmatch %}
{%- endif %}
{%- else %}
  auto __status = ubrn::nitro::make_status();
  // Exception-safe lowering (audit bug #24): the cloned receiver handle, every
  // owning RustBuffer arg, and every interface / callback handle arg are parked
  // in move-only guards, then `.take()`-d into the FFI call only once *all*
  // lowerings have succeeded. If a later arg's lowering throws (a
  // RustBufferWriter alloc, a clone_handle on a zero handle, or a JSIConverter
  // on a bad JS value), the guards free the already-built handle/buffers on
  // unwind instead of leaking them. The success path is move-only — no extra
  // alloc or copy.
  ubrn::nitro::UniffiObjectHandle<&{{ iface.free_symbol }}> __self_guard{clone_handle()};
{%- for arg in method.args %}
  {{ arg.lower_guard_stmt(module.namespace, module.rustbuffer_alloc, module.rustbuffer_reserve) }}
{%- endfor %}
{%- match method.return_kind %}
{%- when crate::bindings::gen_nitro::model::ReturnKind::Void %}
  {{ method.uniffi_symbol }}(__self_guard.take(),
{%- for arg in method.args -%}
    {{ arg.pass_expr() }},
{%- endfor -%}
    &__status);
{%- if let Some(throws) = method.throws %}
  try {
    ubrn::nitro::check_status(__status, free_status_buffer);
  } catch (ubrn::nitro::UniffiTypedError& __typed) {
    // Decode borrows the buffer; __typed frees it on scope exit (even if
    // the decoder itself throws).
    auto __decoded = {{ throws.lift_fn(module.namespace) }}(__typed.buffer());
    throw __decoded;
  }
{%- else %}
  ubrn::nitro::check_status(__status, free_status_buffer);
{%- endif %}
{%- when crate::bindings::gen_nitro::model::ReturnKind::Value with (ret_ty) %}
  auto __raw = {{ method.uniffi_symbol }}(__self_guard.take(),
{%- for arg in method.args -%}
    {{ arg.pass_expr() }},
{%- endfor -%}
    &__status);
{%- if let Some(throws) = method.throws %}
  try {
    ubrn::nitro::check_status(__status, free_status_buffer);
  } catch (ubrn::nitro::UniffiTypedError& __typed) {
    // Decode borrows the buffer; __typed frees it on scope exit (even if
    // the decoder itself throws).
    auto __decoded = {{ throws.lift_fn(module.namespace) }}(__typed.buffer());
    throw __decoded;
  }
{%- else %}
  ubrn::nitro::check_status(__status, free_status_buffer);
{%- endif %}
{%- if method.return_kind.returns_owned_rustbuffer() %}
{%- if ret_ty.lift_consumes_buffer() %}
  // Zero-copy: hand the Rust-owned buffer's payload straight to JS as the
  // ArrayBuffer backing store; freed via the namespace hook on JS GC.
  return {{ ret_ty.lift_owning_expr("__raw", module.namespace, module.rustbuffer_free) }};
{%- else %}
  // RAII: free the Rust-owned return buffer on scope exit, so a throwing
  // lift (malformed payload / OOM) can't leak it.
  ubrn::nitro::RustBufferGuard __raw_guard{__raw, &free_status_buffer};
  return {{ ret_ty.lift_expr("__raw", module.namespace) }};
{%- endif %}
{%- else %}
  return {{ ret_ty.lift_expr("__raw", module.namespace) }};
{%- endif %}
{%- endmatch %}
{%- endif %}
}
{%- endfor %}

} // namespace margelo::nitro::{{ module.namespace }}
