// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// Consumer-facing module for the uniffi `{{ module.namespace }}` crate.
// Re-exports the HybridObject types from the .nitro.ts spec and exposes
// a lazy singleton instance of the namespace API HybridObject.
import { NitroModules } from 'react-native-nitro-modules'
import type {
  {{ module.namespace_api_ts_name() }},
{%- for iface in module.interfaces %}
  {{ iface.ts_name }},
{%- endfor %}
{%- for cb in module.callback_interfaces %}
  {{ cb.ts_name }},
{%- endfor %}
} from './{{ module.namespace_camel }}.nitro'

export type {
  {{ module.namespace_api_ts_name() }},
{%- for iface in module.interfaces %}
  {{ iface.ts_name }},
{%- endfor %}
{%- for cb in module.callback_interfaces %}
  {{ cb.ts_name }},
{%- endfor %}
}

let __cached: {{ module.namespace_api_ts_name() }} | undefined

/**
 * Singleton accessor for the namespace API HybridObject. Idempotent —
 * `NitroModules.createHybridObject` returns the same instance on
 * repeated calls, but we cache locally so the registry lookup happens
 * once per JS module load.
 */
export function {{ module.namespace }}(): {{ module.namespace_api_ts_name() }} {
  if (__cached === undefined) {
    __cached = NitroModules.createHybridObject<{{ module.namespace_api_ts_name() }}>('{{ module.namespace_api_ts_name() }}')
  }
  return __cached
}

// Top-level pass-through exports — match the surface the other backends
// (jsi/napi/wasm) ship so consumer code can import individual functions
// instead of having to dereference the namespace API singleton.
{%- for func in module.functions %}
export function {{ func.ts_name }}(
{%- for arg in func.args -%}
{{ arg.ts_name }}: {{ arg.ty.ts_type() }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
): {{ func.ts_return_signature() }} {
  return {{ module.namespace }}().{{ func.ts_name }}(
{%- for arg in func.args -%}
{{ arg.ts_name }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  )
}
{%- endfor %}
