// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// Namespace API HybridObject impl for uniffi crate `{{ module.crate_name }}`.
#pragma once

#include <NitroModules/HybridObject.hpp>
#include <NitroModules/Promise.hpp>
#include <NitroUniffi.hpp>
#include <nitro-uniffi/jsi_converter_ints.hpp>
#include <nitro-uniffi/jsi_converter_map.hpp>

#include <memory>
#include <optional>
#include <string>
#include <unordered_map>
#include <vector>

// Per-type headers for every record / enum / interface this API's methods
// take or return — ubrn emits these directly (no Nitrogen).
{%- for header in module.api_dependency_headers() %}
#include "{{ header }}"
{%- endfor %}

namespace margelo::nitro::{{ module.namespace }} {

class {{ module.namespace_api_cxx_class() }}
    : public ::margelo::nitro::HybridObject {
public:
  static constexpr auto TAG = "{{ module.namespace_api_ts_name() }}";

  {{ module.namespace_api_cxx_class() }}() : HybridObject(TAG) {}
{%- for func in module.api_methods() %}
  {{ func.cxx_return_signature() }} {{ func.cxx_name }}(
{%- for arg in func.args -%}
    {{ arg.ty.cxx_type() }} {{ arg.ts_name }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  );
{%- endfor %}

protected:
  void loadHybridMethods() override;
};

} // namespace margelo::nitro::{{ module.namespace }}
