// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// Consumer-facing module for the uniffi `{{ module.namespace }}` crate.
// Re-exports the record / enum / HybridObject types from the .nitro.ts
// spec, exposes a lazy singleton of the namespace API HybridObject, and
// vends each uniffi interface as a constructable class shim.
import { NitroModules } from 'react-native-nitro-modules'
import type {
  {{ module.namespace_api_ts_name() }},
{%- for record in module.records %}
  {{ record.ts_name }},
{%- endfor %}
{%- for en in module.enums %}
  {{ en.ts_name }},
{%- endfor %}
{%- for iface in module.interfaces %}
  {{ iface.ts_name }} as {{ iface.ts_name }}Spec,
{%- endfor %}
{%- for cb in module.callback_interfaces %}
  {{ cb.ts_name }} as {{ cb.ts_name }}Spec,
{%- endfor %}
} from './{{ module.namespace_camel }}.nitro'

// Record / enum / callback types and the namespace-API + interface *types*
// pass straight through. Interfaces also get a runtime value (the class
// shim below), so they're exported as `type` here under the `Spec` alias
// and re-surfaced under their bare name as a class. Callback interfaces are
// re-exported as `type` under a `Spec` alias too: their bare name becomes a
// runtime *factory* (the JS-impl wrapper) emitted further down.
export type {
  {{ module.namespace_api_ts_name() }},
{%- for record in module.records %}
  {{ record.ts_name }},
{%- endfor %}
{%- for en in module.enums %}
  {{ en.ts_name }},
{%- endfor %}
{%- for cb in module.callback_interfaces %}
  {{ cb.ts_name }} as {{ cb.ts_name }}Spec,
{%- endfor %}
}

let __cached: {{ module.namespace_api_ts_name() }} | undefined

/**
 * Singleton accessor for the namespace API HybridObject. Idempotent —
 * `NitroModules.createHybridObject` returns the same instance on
 * repeated calls, but we cache locally so the registry lookup happens
 * once per JS module load.
 */
export function {{ module.namespace }}(): {{ module.namespace_api_ts_name() }} {
  if (__cached === undefined) {
    __cached = NitroModules.createHybridObject<{{ module.namespace_api_ts_name() }}>('{{ module.namespace_api_ts_name() }}')
  }
  return __cached
}

{%- for iface in module.interfaces %}
{%- if iface.primary_constructor().is_some() %}

/**
 * Runtime surface for the uniffi interface `{{ iface.ts_name }}`. Each
 * `new {{ iface.ts_name }}()` calls `NitroModules.createHybridObject`,
 * whose C++ default constructor drives the underlying uniffi constructor.
 * The constructor returns the HybridObject directly, so the instance is a
 * live `{{ iface.ts_name }}` (matching the other backends' class surface).
 */
export const {{ iface.ts_name }} = class {
  constructor() {
    return NitroModules.createHybridObject<{{ iface.ts_name }}Spec>('{{ iface.ts_name }}')
  }
} as unknown as { new (): {{ iface.ts_name }}Spec }
export type {{ iface.ts_name }} = {{ iface.ts_name }}Spec
{%- else %}

/**
 * The uniffi interface `{{ iface.ts_name }}` has no argless/sync/infallible
 * constructor, so there is no `new {{ iface.ts_name }}()` — Nitro's argless
 * `createHybridObject` path can only drive a default constructor.
{%- if !iface.factories.is_empty() %}
 * Construct instances via the `create{{ iface.ts_name }}*` factory
 * function(s) below (or receive them from method / function returns).
{%- else %}
 * Instances are obtained from method / function returns.
{%- endif %}
 */
export type {{ iface.ts_name }} = {{ iface.ts_name }}Spec
{%- endif %}
{%- endfor %}

{%- for cb in module.callback_interfaces %}
{%- if cb.has_js_impl_methods() %}

/**
 * JS-impl factory for the uniffi callback interface `{{ cb.ts_name }}`.
 *
 * The other backends (jsi/napi/wasm) let JS pass a plain object that
 * `implements {{ cb.ts_name }}`. Under Nitro a callback parameter is a
 * `HybridObject`, so a bare object is rejected by the argument's JSI
 * converter (it has no C++ `NativeState`). This factory bridges the gap:
 * it creates the generated `{{ cb.cxx_class }}` HybridObject and binds the
 * supplied `impl`'s methods onto it via the C++ `setJsImpl` hook. The
 * returned value IS a `{{ cb.ts_name }}` and can be handed straight to any
 * method taking one — Rust dispatches into `impl`'s methods (async methods
 * are awaited through uniffi's foreign-future ABI).
 *
 * Call it as a function (`{{ cb.ts_name }}(impl)`); the bare name doubles as
 * the interface *type* (declaration merging), so `const cb: {{ cb.ts_name }}
 * = {{ cb.ts_name }}(impl)` type-checks.
 */
export function {{ cb.ts_name }}(impl: {
{%- for method in cb.methods %}
  {{ method.ts_name }}(
{%- for arg in method.args -%}
    {{ arg.ts_name }}: {{ arg.ty.ts_type() }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  ): {{ method.ts_return_signature() }}
{%- endfor %}
}): {{ cb.ts_name }}Spec {
  const __obj = NitroModules.createHybridObject<{{ cb.ts_name }}Spec>('{{ cb.ts_name }}')
  // The C++ `setJsImpl` hook isn't part of the public spec surface; it takes
  // one bound function per JS-impl-supported method, in declaration order.
  // (Async-void methods, if any, are omitted — see the C++ `supports_js_impl`
  // rationale; they keep the proxy / throw fallback.)
  ;(__obj as unknown as { setJsImpl(
{%- for method in cb.js_impl_methods() -%}
    {{ method.cxx_name }}_fn: (
{%- for arg in method.args -%}
      {{ arg.ts_name }}: {{ arg.ty.ts_type() }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
    ) => {{ method.ts_return_signature() }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  ): void }).setJsImpl(
{%- for method in cb.js_impl_methods() -%}
    impl.{{ method.ts_name }}.bind(impl){% if !loop.last %}, {% endif %}
{%- endfor -%}
  )
  return __obj
}
export type {{ cb.ts_name }} = {{ cb.ts_name }}Spec
{%- else %}

/**
 * The uniffi callback interface `{{ cb.ts_name }}` has no method the Nitro
 * JS-impl bridge can support (every method is an async `void`-returning
 * method, which Nitro's `std::function` callback converter can't round-trip
 * as an awaitable). It is therefore type-only here — JS cannot supply an
 * impl for it under Nitro yet.
 */
export type {{ cb.ts_name }} = {{ cb.ts_name }}Spec
{%- endif %}
{%- endfor %}

// Top-level pass-through exports — match the surface the other backends
// (jsi/napi/wasm) ship so consumer code can import individual functions
// instead of having to dereference the namespace API singleton. Includes
// the `create<Interface>` constructor factories for interfaces whose
// construction takes arguments / is async / is fallible (Nitro's argless
// `new <Interface>()` shim can't drive those).
{%- for func in module.api_methods() %}
export function {{ func.ts_name }}(
{%- for arg in func.args -%}
{{ arg.ts_name }}: {{ arg.ty.ts_type() }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
): {{ func.ts_return_signature() }} {
  return {{ module.namespace }}().{{ func.ts_name }}(
{%- for arg in func.args -%}
{{ arg.ts_name }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  )
}
{%- endfor %}
