// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// Namespace API HybridObject impl for uniffi crate `{{ module.crate_name }}`.
#pragma once

#include <NitroModules/HybridObject.hpp>
#include <NitroUniffi.hpp>

#include <string>

namespace margelo::nitro::{{ module.namespace }} {

class {{ module.namespace_api_cxx_class() }}
    : public ::margelo::nitro::HybridObject {
public:
  static constexpr auto TAG = "{{ module.namespace_api_ts_name() }}";

  {{ module.namespace_api_cxx_class() }}() : HybridObject(TAG) {}
{%- for func in module.functions %}
  {{ func.cxx_return_signature() }} {{ func.cxx_name }}(
{%- for arg in func.args -%}
    {{ arg.ty.cxx_type() }} {{ arg.ts_name }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  );
{%- endfor %}

protected:
  void loadHybridMethods() override;
};

} // namespace margelo::nitro::{{ module.namespace }}
