// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// Namespace API HybridObject impl for uniffi crate `{{ module.crate_name }}`.
//
// Every method here is a direct call into the uniffi C ABI. The
// nitro-uniffi helpers handle lowering/lifting; we just hand the
// generated symbols + buffer-management hooks to them.
#include "{{ module.namespace_api_cxx_class() }}.hpp"
#include "{{ module.codecs_header_filename() }}"

#include <NitroModules/Promise.hpp>

extern "C" {
RustBuffer {{ module.rustbuffer_alloc }}(uint64_t size, UniffiRustCallStatus* status);
void {{ module.rustbuffer_free }}(RustBuffer buf, UniffiRustCallStatus* status);
RustBuffer {{ module.rustbuffer_reserve }}(RustBuffer buf, uint64_t add, UniffiRustCallStatus* status);

{%- for func in module.api_methods() %}
{%- if func.is_async %}
// Async scaffolding for `{{ func.cxx_name }}` — `_fn_func_*` returns a
// uint64 RustFuture handle; the value-FFI return is produced by the
// matching `rust_future_complete_*` symbol below.
uint64_t {{ func.uniffi_symbol }}(
{%- if func.args.is_empty() %} void {%- endif %}
{%- for arg in func.args -%}
    {{ arg.ty.c_type() }} {{ arg.ts_name }}_lowered{% if !loop.last %}, {% endif %}
{%- endfor -%}
);
{%- if let Some(ad) = func.async_data %}
void {{ ad.poll_symbol }}(uint64_t handle, void (*cb)(uint64_t, int8_t), uint64_t cb_data);
void {{ ad.free_symbol }}(uint64_t handle);
// uniffi async cancel — one arg (the future handle), void return, no status.
void {{ ad.cancel_symbol }}(uint64_t handle);
{{ func.return_kind.c_type() }} {{ ad.complete_symbol }}(uint64_t handle, UniffiRustCallStatus* status);
{%- endif %}
{%- else %}
{{ func.return_kind.c_type() }} {{ func.uniffi_symbol }}(
{%- for arg in func.args -%}
    {{ arg.ty.c_type() }} {{ arg.ts_name }}_lowered,
{%- endfor -%}
    UniffiRustCallStatus* status
);
{%- endif %}
{%- endfor %}
}

namespace margelo::nitro::{{ module.namespace }} {

void {{ module.namespace_api_cxx_class() }}::loadHybridMethods() {
  HybridObject::loadHybridMethods();
  registerHybrids(this, [](Prototype& prototype) {
{%- for func in module.api_methods() %}
    prototype.registerHybridMethod("{{ func.ts_name }}", &{{ module.namespace_api_cxx_class() }}::{{ func.cxx_name }});
{%- endfor %}
{%- if module.has_async_api_methods() %}
    // Non-spec async-cancellation hooks (see the `.hpp` declaration + the
    // `.ts` wrapper's `__uniffiBeginAbortable` / `__uniffiAbort` usage).
    prototype.registerHybridMethod("__uniffiBeginAbortable", &{{ module.namespace_api_cxx_class() }}::__uniffiBeginAbortable);
    prototype.registerHybridMethod("__uniffiAbort", &{{ module.namespace_api_cxx_class() }}::__uniffiAbort);
{%- endif %}
  });
}

{%- if module.has_async_api_methods() %}
double {{ module.namespace_api_cxx_class() }}::__uniffiBeginAbortable() {
  return static_cast<double>(::ubrn::nitro::begin_abortable_future());
}

void {{ module.namespace_api_cxx_class() }}::__uniffiAbort(double token) {
  ::ubrn::nitro::abort_rust_future(static_cast<uint64_t>(token));
}
{%- endif %}

{%- for func in module.api_methods() %}
{{ func.cxx_return_signature() }} {{ module.namespace_api_cxx_class() }}::{{ func.cxx_name }}(
{%- for arg in func.args -%}
    {{ arg.ty.cxx_type() }} {{ arg.ts_name }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
) {
{%- if func.is_async %}
{%- if let Some(ad) = func.async_data %}
  // Exception-safe lowering (audit bug #24): owning RustBuffer args and
  // interface / callback handle args are parked in move-only guards and
  // `.take()`-d into the kick-off only after every lowering has succeeded, so a
  // throw mid-prologue frees the already-built buffers / handles instead of
  // leaking them. Free functions have no receiver handle to guard.
{%- for arg in func.args %}
  {{ arg.lower_guard_stmt(module.namespace, module.rustbuffer_alloc, module.rustbuffer_reserve) }}
{%- endfor %}
  // Kick off the future eagerly: lowered-arg ownership transfers to Rust at
  // this call. We then arm the uniffi continuation and resolve the Promise
  // event-driven (no worker thread / blocking wait) — see
  // `drive_rust_future_async`.
  uint64_t __handle = {{ func.uniffi_symbol }}(
{%- for arg in func.args -%}
    {{ arg.pass_expr() }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  );
{%- match func.return_kind %}
{%- when crate::bindings::gen_nitro::model::ReturnKind::Void %}
  return ::ubrn::nitro::drive_rust_future_async_void(
      __handle, &{{ ad.poll_symbol }}, &{{ ad.free_symbol }},
      [__handle]() {
        auto __status = ::ubrn::nitro::make_status();
        {{ ad.complete_symbol }}(__handle, &__status);
{%- if let Some(throws) = func.throws %}
        try {
          ::ubrn::nitro::check_status(__status, free_status_buffer);
        } catch (::ubrn::nitro::UniffiTypedError& __typed) {
          throw {{ throws.lift_fn(module.namespace) }}(__typed.buffer());
        }
{%- else %}
        ::ubrn::nitro::check_status(__status, free_status_buffer);
{%- endif %}
      },
      &{{ ad.cancel_symbol }});
{%- when crate::bindings::gen_nitro::model::ReturnKind::Value with (ret_ty) %}
  return ::ubrn::nitro::drive_rust_future_async<{{ ret_ty.cxx_type() }}>(
      __handle, &{{ ad.poll_symbol }}, &{{ ad.free_symbol }},
      [__handle]() -> {{ ret_ty.cxx_type() }} {
        auto __status = ::ubrn::nitro::make_status();
        auto __raw = {{ ad.complete_symbol }}(__handle, &__status);
{%- if let Some(throws) = func.throws %}
        try {
          ::ubrn::nitro::check_status(__status, free_status_buffer);
        } catch (::ubrn::nitro::UniffiTypedError& __typed) {
          throw {{ throws.lift_fn(module.namespace) }}(__typed.buffer());
        }
{%- else %}
        ::ubrn::nitro::check_status(__status, free_status_buffer);
{%- endif %}
{%- if func.return_kind.returns_owned_rustbuffer() %}
{%- if ret_ty.lift_consumes_buffer() %}
        return {{ ret_ty.lift_owning_expr("__raw", module.namespace, module.rustbuffer_free) }};
{%- else %}
        ::ubrn::nitro::RustBufferGuard __raw_guard{__raw, &free_status_buffer};
        return {{ ret_ty.lift_expr("__raw", module.namespace) }};
{%- endif %}
{%- else %}
        return {{ ret_ty.lift_expr("__raw", module.namespace) }};
{%- endif %}
      },
      &{{ ad.cancel_symbol }});
{%- endmatch %}
{%- endif %}
{%- else %}
  auto __status = ubrn::nitro::make_status();
  // Exception-safe lowering (audit bug #24): owning RustBuffer args and
  // interface / callback handle args are parked in move-only guards and
  // `.take()`-d into the FFI call only once every lowering has succeeded, so a
  // throw mid-prologue frees the already-built buffers / handles instead of
  // leaking them. Free functions have no receiver handle to guard.
{%- for arg in func.args %}
  {{ arg.lower_guard_stmt(module.namespace, module.rustbuffer_alloc, module.rustbuffer_reserve) }}
{%- endfor %}
{%- match func.return_kind %}
{%- when crate::bindings::gen_nitro::model::ReturnKind::Void %}
  {{ func.uniffi_symbol }}(
{%- for arg in func.args -%}
    {{ arg.pass_expr() }},
{%- endfor -%}
    &__status);
{%- if let Some(throws) = func.throws %}
  try {
    ubrn::nitro::check_status(__status, free_status_buffer);
  } catch (ubrn::nitro::UniffiTypedError& __typed) {
    // Decode borrows the buffer; __typed frees it on scope exit (even if
    // the decoder itself throws).
    auto __decoded = {{ throws.lift_fn(module.namespace) }}(__typed.buffer());
    throw __decoded;
  }
{%- else %}
  ubrn::nitro::check_status(__status, free_status_buffer);
{%- endif %}
{%- when crate::bindings::gen_nitro::model::ReturnKind::Value with (ret_ty) %}
  auto __raw = {{ func.uniffi_symbol }}(
{%- for arg in func.args -%}
    {{ arg.pass_expr() }},
{%- endfor -%}
    &__status);
{%- if let Some(throws) = func.throws %}
  try {
    ubrn::nitro::check_status(__status, free_status_buffer);
  } catch (ubrn::nitro::UniffiTypedError& __typed) {
    // Decode borrows the buffer; __typed frees it on scope exit (even if
    // the decoder itself throws).
    auto __decoded = {{ throws.lift_fn(module.namespace) }}(__typed.buffer());
    throw __decoded;
  }
{%- else %}
  ubrn::nitro::check_status(__status, free_status_buffer);
{%- endif %}
{%- if func.return_kind.returns_owned_rustbuffer() %}
{%- if ret_ty.lift_consumes_buffer() %}
  // Zero-copy: hand the Rust-owned buffer's payload straight to JS as the
  // ArrayBuffer backing store; it's freed via the namespace free hook when
  // JS garbage-collects the ArrayBuffer.
  return {{ ret_ty.lift_owning_expr("__raw", module.namespace, module.rustbuffer_free) }};
{%- else %}
  // RAII: free the Rust-owned return buffer on scope exit, so a throwing
  // lift (malformed payload / OOM) can't leak it.
  ubrn::nitro::RustBufferGuard __raw_guard{__raw, &free_status_buffer};
  return {{ ret_ty.lift_expr("__raw", module.namespace) }};
{%- endif %}
{%- else %}
  return {{ ret_ty.lift_expr("__raw", module.namespace) }};
{%- endif %}
{%- endmatch %}
{%- endif %}
}
{%- endfor %}

} // namespace margelo::nitro::{{ module.namespace }}
