// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// Source uniffi namespace: {{ module.namespace }}
import type { HybridObject } from 'react-native-nitro-modules'
{%- for imp in module.foreign_ts_type_imports() %}
import type { {% for name in imp.type_names %}{{ name }}{% if !loop.last %}, {% endif %}{% endfor %} } from '{{ imp.module_path }}'
{%- endfor %}

{% for record in module.records %}
/**
 * Uniffi record `{{ record.ts_name }}`. ubrn emits the C++ struct + its
 * `JSIConverter` in `{{ record.ts_name }}.hpp` and the RustBuffer codec
 * (`lift_{{ record.ts_name }}` / `lower_{{ record.ts_name }}`) in
 * `{{ module.namespace }}_codecs.hpp` — no Nitrogen involved.
 */
export interface {{ record.ts_name }} {
{%- for field in record.fields %}
  {{ field.ts_name }}: {{ field.ty.ts_type() }}
{%- endfor %}
}
{% endfor %}
{% for en in module.enums %}
/**
 * Uniffi enum `{{ en.ts_name }}`.
 */
{%- if en.flat %}
export type {{ en.ts_name }} = {% for variant in en.variants %}'{{ variant.ts_name }}'{% if !loop.last %} | {% endif %}{% endfor %}
{%- else %}
// Discriminated union keyed on `tag` (the UpperCamelCase variant name),
// payload nested under `inner` — byte-for-byte the standard uniffi
// tagged-enum runtime shape the NAPI/JSI backends emit, so a value built by
// the shared `@<scope>/<crate>-js` layer (or any other ubrn target)
// round-trips through the `JSIConverter` ubrn emits in `{{ en.ts_name }}.hpp`.
export type {{ en.ts_name }} =
{%- for variant in en.variants %}
{%- let has_fields = !variant.fields.is_empty() %}
  | { tag: '{{ variant.ts_name }}'{% if has_fields %}; inner: {% if variant.has_nameless_fields %}Readonly<[{% for field in variant.fields %}{{ field.ty.ts_type() }}{% if !loop.last %}, {% endif %}{% endfor %}]>{% else %}Readonly<{ {% for field in variant.fields %}{{ field.ts_name }}: {{ field.ty.ts_type() }}{% if !loop.last %}; {% endif %}{% endfor %} }>{% endif %}{% endif %} }
{%- endfor %}
{%- endif %}
{% endfor %}
{% for err in module.errors %}
/**
 * Uniffi error `{{ err.ts_name }}`. Methods that declare
 * `throws({{ err.ts_name }})` reject their Promise (or throw, for sync
 * methods) with a JS Error whose `kind` matches one of the variant tags
 * below. The C++ side throws a `{{ err.ts_name }}Error` instance; Nitro's
 * `HybridFunction::callMethod` translates that into a `jsi::JSError`.
 *
 * For data-carrying variants the decoded fields are rendered into the JS
 * `error.message` as `{{ err.ts_name }}::<Variant>(field=value, ...)`, so
 * the payload uniffi serialized after the variant tag is not lost.
 */
{%- if err.flat %}
export type {{ err.ts_name }}Variant = {% for variant in err.variants %}'{{ variant.ts_name }}'{% if !loop.last %} | {% endif %}{% endfor %}
{%- else %}
export type {{ err.ts_name }}Variant = {% for variant in err.variants %}{ tag: '{{ variant.ts_name }}' }{% if !loop.last %} | {% endif %}{% endfor %}
{%- endif %}
{% endfor %}

/**
 * Namespace API for the uniffi `{{ module.namespace }}` crate. Hosts every
 * top-level function. Obtain a singleton via
 * `NitroModules.createHybridObject<{{ module.namespace_api_ts_name() }}>('{{ module.namespace_api_ts_name() }}')`.
 */
export interface {{ module.namespace_api_ts_name() }} extends HybridObject<{
  ios: 'c++'
  android: 'c++'
}> {
{%- for func in module.api_methods() %}
  {{ func.ts_name }}(
{%- for arg in func.args -%}
    {{ arg.ts_name }}: {{ arg.ty.ts_type() }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  ): {{ func.ts_return_signature() }}
{%- endfor %}
}

{% for iface in module.interfaces %}
/**
 * Uniffi interface `{{ iface.ts_name }}`. Each method invokes the
 * corresponding uniffi C ABI symbol from the C++ impl class
 * `{{ iface.cxx_class }}`.
 */
export interface {{ iface.ts_name }} extends HybridObject<{
  ios: 'c++'
  android: 'c++'
}> {
{%- for method in iface.methods %}
  {{ method.ts_name }}(
{%- for arg in method.args -%}
    {{ arg.ts_name }}: {{ arg.ty.ts_type() }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  ): {{ method.ts_return_signature() }}
{%- endfor %}
}
{% endfor %}

{% for cb in module.callback_interfaces %}
/**
 * Uniffi callback interface `{{ cb.ts_name }}`. JS-side implements every
 * method; the generated C++ trampoline class `{{ cb.cxx_class }}`
 * registers a vtable with Rust on first use so Rust can dispatch into
 * the JS impl via the `CallbackHandleMap`.
 *
 * The HybridObject extension makes Nitrogen emit a base spec
 * (`Hybrid{{ cb.ts_name }}Spec`) that user code subclasses on the JS
 * side, then hands to a method that takes this type as an argument.
 */
export interface {{ cb.ts_name }} extends HybridObject<{
  ios: 'c++'
  android: 'c++'
}> {
{%- for method in cb.methods %}
  {{ method.ts_name }}(
{%- for arg in method.args -%}
    {{ arg.ts_name }}: {{ arg.ty.ts_type() }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  ): {{ method.ts_return_signature() }}
{%- endfor %}
}
{% endfor %}
