// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// Consumer-facing module for the uniffi `{{ module.namespace }}` crate.
// Re-exports the record / enum / HybridObject types from the .nitro.ts
// spec, exposes a lazy singleton of the namespace API HybridObject, and
// vends each uniffi interface as a constructable class shim.
import { NitroModules } from 'react-native-nitro-modules'
import type {
  {{ module.namespace_api_ts_name() }},
{%- for record in module.records %}
  {{ record.ts_name }},
{%- endfor %}
{%- for en in module.enums %}
  {{ en.ts_name }},
{%- endfor %}
{%- for iface in module.interfaces %}
  {{ iface.ts_name }} as {{ iface.ts_name }}Spec,
{%- endfor %}
{%- for cb in module.callback_interfaces %}
  {{ cb.ts_name }},
{%- endfor %}
} from './{{ module.namespace_camel }}.nitro'

// Record / enum / callback types and the namespace-API + interface *types*
// pass straight through. Interfaces also get a runtime value (the class
// shim below), so they're exported as `type` here under the `Spec` alias
// and re-surfaced under their bare name as a class.
export type {
  {{ module.namespace_api_ts_name() }},
{%- for record in module.records %}
  {{ record.ts_name }},
{%- endfor %}
{%- for en in module.enums %}
  {{ en.ts_name }},
{%- endfor %}
{%- for cb in module.callback_interfaces %}
  {{ cb.ts_name }},
{%- endfor %}
}

let __cached: {{ module.namespace_api_ts_name() }} | undefined

/**
 * Singleton accessor for the namespace API HybridObject. Idempotent —
 * `NitroModules.createHybridObject` returns the same instance on
 * repeated calls, but we cache locally so the registry lookup happens
 * once per JS module load.
 */
export function {{ module.namespace }}(): {{ module.namespace_api_ts_name() }} {
  if (__cached === undefined) {
    __cached = NitroModules.createHybridObject<{{ module.namespace_api_ts_name() }}>('{{ module.namespace_api_ts_name() }}')
  }
  return __cached
}

{%- for iface in module.interfaces %}

/**
 * Runtime surface for the uniffi interface `{{ iface.ts_name }}`. Each
 * `new {{ iface.ts_name }}()` calls `NitroModules.createHybridObject`,
 * whose C++ default constructor drives the underlying uniffi constructor.
 * The constructor returns the HybridObject directly, so the instance is a
 * live `{{ iface.ts_name }}` (matching the other backends' class surface).
 */
export const {{ iface.ts_name }} = class {
  constructor() {
    return NitroModules.createHybridObject<{{ iface.ts_name }}Spec>('{{ iface.ts_name }}')
  }
} as unknown as { new (): {{ iface.ts_name }}Spec }
export type {{ iface.ts_name }} = {{ iface.ts_name }}Spec
{%- endfor %}

// Top-level pass-through exports — match the surface the other backends
// (jsi/napi/wasm) ship so consumer code can import individual functions
// instead of having to dereference the namespace API singleton.
{%- for func in module.functions %}
export function {{ func.ts_name }}(
{%- for arg in func.args -%}
{{ arg.ts_name }}: {{ arg.ty.ts_type() }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
): {{ func.ts_return_signature() }} {
  return {{ module.namespace }}().{{ func.ts_name }}(
{%- for arg in func.args -%}
{{ arg.ts_name }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  )
}
{%- endfor %}
