// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// C++ struct + JSIConverter for uniffi record `{{ record.ts_name }}` in
// namespace `{{ module.namespace }}`.
//
// This is the single source of truth for the record's C++ representation:
// ubrn emits it directly (no Nitrogen). The struct mirrors the field
// order/types uniffi's metadata reports; the `JSIConverter` specialization
// marshals it to/from a JS plain object field-by-field, delegating each
// field to its own `JSIConverter<T>` (Nitro core ships those for
// primitives / string / optional / vector / map; nested records/enums
// recurse through their own emitted converters).
#pragma once

#include <NitroModules/JSIConverter.hpp>
#include <NitroModules/JSIHelpers.hpp>
#include <NitroModules/PropNameIDCache.hpp>

#include <NitroUniffi.hpp>
#include <nitro-uniffi/jsi_converter_ints.hpp>

#include <optional>
#include <string>
#include <unordered_map>
#include <variant>
#include <vector>
{%- for header in record.dependency_headers() %}
#include "{{ header }}"
{%- endfor %}

namespace margelo::nitro::{{ module.namespace }} {

/**
 * Uniffi record `{{ record.ts_name }}`, as a JS-object-shaped struct.
 */
struct {{ record.ts_name }} final {
public:
{%- for field in record.fields %}
  {{ field.ty.cxx_type() }} {{ field.ts_name }};
{%- endfor %}

public:
  {{ record.ts_name }}() = default;
  explicit {{ record.ts_name }}(
{%- for field in record.fields -%}
    {{ field.ty.cxx_type() }} {{ field.ts_name }}{% if !loop.last %}, {% endif %}
{%- endfor -%}
  )
{%- if !record.fields.is_empty() %}:
{%- for field in record.fields -%}
    {{ field.ts_name }}(std::move({{ field.ts_name }})){% if !loop.last %}, {% endif %}
{%- endfor -%}
{%- endif %} {}

public:
  friend bool operator==(const {{ record.ts_name }}& lhs, const {{ record.ts_name }}& rhs) = default;
};

} // namespace margelo::nitro::{{ module.namespace }}

namespace margelo::nitro {

// C++ {{ record.ts_name }} <> JS {{ record.ts_name }} (object)
template <>
struct JSIConverter<margelo::nitro::{{ module.namespace }}::{{ record.ts_name }}> final {
  static inline margelo::nitro::{{ module.namespace }}::{{ record.ts_name }}
  fromJSI(jsi::Runtime& runtime, const jsi::Value& arg) {
    jsi::Object obj = arg.asObject(runtime);
    return margelo::nitro::{{ module.namespace }}::{{ record.ts_name }}(
{%- for field in record.fields %}
      JSIConverter<{{ field.ty.cxx_type() }}>::fromJSI(runtime, obj.getProperty(runtime, PropNameIDCache::get(runtime, "{{ field.ts_name }}"))){% if !loop.last %},{% endif %}
{%- endfor %}
    );
  }
  static inline jsi::Value
  toJSI(jsi::Runtime& runtime, const margelo::nitro::{{ module.namespace }}::{{ record.ts_name }}& arg) {
    jsi::Object obj(runtime);
{%- for field in record.fields %}
    obj.setProperty(runtime, PropNameIDCache::get(runtime, "{{ field.ts_name }}"), JSIConverter<{{ field.ty.cxx_type() }}>::toJSI(runtime, arg.{{ field.ts_name }}));
{%- endfor %}
    return obj;
  }
  static inline bool canConvert(jsi::Runtime& runtime, const jsi::Value& value) {
    if (!value.isObject()) {
      return false;
    }
    jsi::Object obj = value.getObject(runtime);
    if (!nitro::isPlainObject(runtime, obj)) {
      return false;
    }
{%- for field in record.fields %}
    if (!JSIConverter<{{ field.ty.cxx_type() }}>::canConvert(runtime, obj.getProperty(runtime, PropNameIDCache::get(runtime, "{{ field.ts_name }}")))) return false;
{%- endfor %}
    return true;
  }
};

} // namespace margelo::nitro
