// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
// Out-of-line `JSIConverter<{{ record.ts_name }}>` definition for a record in a
// header `#include` cycle. Included (idempotently, from every cycle member's
// header) *after* all the cycle's structs are complete; the guard below makes
// it expand exactly once — when every struct sentinel is set and this
// converter hasn't been defined yet. Out-of-lining the bodies keeps them from
// being instantiated before the partner types exist. No `#pragma once`: the
// guard is the include guard, and the footer must be re-evaluable on each
// inclusion so it can fire on whichever pass first sees all structs complete.

#if defined(UBRN_CYC_{{ module.namespace }}_{{ record.ts_name }}_STRUCT) \
{%- for partner in record.cycle_partners %}
  && defined({{ partner.struct_sentinel }}) \
{%- endfor %}
  && !defined(UBRN_CYC_{{ module.namespace }}_{{ record.ts_name }}_CONV)
#define UBRN_CYC_{{ module.namespace }}_{{ record.ts_name }}_CONV 1

namespace margelo::nitro {

inline margelo::nitro::{{ module.namespace }}::{{ record.ts_name }}
JSIConverter<margelo::nitro::{{ module.namespace }}::{{ record.ts_name }}>::fromJSI(jsi::Runtime& runtime, const jsi::Value& arg) {
  jsi::Object obj = arg.asObject(runtime);
  return margelo::nitro::{{ module.namespace }}::{{ record.ts_name }}(
{%- for field in record.fields %}
    JSIConverter<{{ field.ty.cxx_type() }}>::fromJSI(runtime, obj.getProperty(runtime, PropNameIDCache::get(runtime, "{{ field.ts_name }}"))){% if !loop.last %},{% endif %}
{%- endfor %}
  );
}

inline jsi::Value
JSIConverter<margelo::nitro::{{ module.namespace }}::{{ record.ts_name }}>::toJSI(jsi::Runtime& runtime, const margelo::nitro::{{ module.namespace }}::{{ record.ts_name }}& arg) {
  jsi::Object obj(runtime);
{%- for field in record.fields %}
  obj.setProperty(runtime, PropNameIDCache::get(runtime, "{{ field.ts_name }}"), JSIConverter<{{ field.ty.cxx_type() }}>::toJSI(runtime, arg.{{ field.cxx_name }}));
{%- endfor %}
  return obj;
}

inline bool
JSIConverter<margelo::nitro::{{ module.namespace }}::{{ record.ts_name }}>::canConvert(jsi::Runtime& runtime, const jsi::Value& value) {
  if (!value.isObject()) {
    return false;
  }
  jsi::Object obj = value.getObject(runtime);
  if (!nitro::isPlainObject(runtime, obj)) {
    return false;
  }
{%- for field in record.fields %}
  if (!JSIConverter<{{ field.ty.cxx_type() }}>::canConvert(runtime, obj.getProperty(runtime, PropNameIDCache::get(runtime, "{{ field.ts_name }}")))) return false;
{%- endfor %}
  return true;
}

} // namespace margelo::nitro

#endif
