// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
//
// We emit our own registration glue and depend ONLY on the
// react-native-nitro-modules RUNTIME — nitrogen is never invoked.
//
// Registration happens automatically at library-load time via a static
// initializer (`register_on_load` below). This runs on every platform the
// moment the shared library is mapped in:
//   * Android: `System.loadLibrary("<module>")`
//   * iOS:     dynamic link / load
//   * Desktop: `dlopen`
// so the HybridObjectRegistry is populated before any JS calls
// `NitroModules.createHybridObject<T>()`.
//
// `extern "C" void registerNatives(jsi::Runtime&)` is kept for the desktop
// Nitro test runner (`cpp/test-harness/test-runner-nitro.cpp`), which
// `dlsym`s and calls it after `dlopen`. Both the static initializer and an
// explicit `registerNatives()` call funnel through a `std::once_flag`, so
// registration is idempotent and never happens twice.

#include <NitroModules/HybridObjectRegistry.hpp>
#include <jsi/jsi.h>
#include <memory>
#include <mutex>

{%- for entry in hybrid_objects %}
// Pulls the impl in so the symbol is available at link time.
#include "{{ entry.cxx_class }}.hpp"
{%- endfor %}

namespace {
// Guards `register_natives_impl` so the constructors are inserted into the
// process-global `HybridObjectRegistry` exactly once, regardless of whether
// the static initializer, the test runner, or both reach this code.
std::once_flag g_register_once;

void register_natives_impl() {
  using namespace margelo::nitro;
{%- for entry in hybrid_objects %}
  HybridObjectRegistry::registerHybridObjectConstructor(
      "{{ entry.name }}",
      []() -> std::shared_ptr<HybridObject> {
        return std::make_shared<::margelo::nitro::{{ entry.cxx_namespace }}::{{ entry.cxx_class }}>();
      });
{%- endfor %}
}

// Static initializer: its constructor runs at library-load time on all
// platforms (Android `System.loadLibrary`, iOS load, desktop `dlopen`),
// before any user code, so HybridObjects are ready immediately.
struct RegisterOnLoad {
  RegisterOnLoad() {
    std::call_once(g_register_once, register_natives_impl);
  }
};
RegisterOnLoad register_on_load;
} // namespace

extern "C" void registerNatives(facebook::jsi::Runtime& /*runtime*/) {
  // Runtime is unused: Nitro's HybridObjectRegistry is process-global, and
  // the host runner installs the Dispatcher separately via `installNitro`.
  // We keep the `jsi::Runtime&` param only so the dlsym signature is stable
  // across loaders. The `std::once_flag` makes this a no-op if the static
  // initializer above has already registered (the common mobile case).
  std::call_once(g_register_once, register_natives_impl);
}
