// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
//
// `registerNatives` is the single entry point the desktop Nitro test
// runner (`cpp/test-harness-nitro/test-runner-nitro.cpp`) invokes after
// `dlopen`ing this shared library. Mobile builds bypass this function:
// Android's `JNI_OnLoad` (emitted to `android/cpp-adapter.cpp` by the
// platform-glue layer) calls the same `registerAllNatives` underneath,
// and iOS's `+ load`-time Nitrogen autolinking does the same.

#include <NitroModules/HybridObjectRegistry.hpp>
#include <jsi/jsi.h>
#include <memory>

{%- for entry in hybrid_objects %}
// Pulls the impl in so the symbol is available at link time.
#include "{{ entry.cxx_class }}.hpp"
{%- endfor %}

extern "C" void registerNatives(facebook::jsi::Runtime& /*runtime*/) {
  using namespace margelo::nitro;
  // Runtime is unused: Nitro's HybridObjectRegistry is process-global, and
  // the desktop runner installs the Dispatcher separately via
  // `installNitro`. We keep the `jsi::Runtime&` param only so the
  // dlsym signature is stable across loaders.
{%- for entry in hybrid_objects %}
  HybridObjectRegistry::registerHybridObjectConstructor(
      "{{ entry.name }}",
      []() -> std::shared_ptr<HybridObject> {
        return std::make_shared<::margelo::nitro::{{ entry.cxx_namespace }}::{{ entry.cxx_class }}>();
      });
{%- endfor %}
}
