// Generated by uniffi-bindgen-react-native (Nitro backend) — DO NOT EDIT.
//
// We emit our own registration glue and depend ONLY on the
// react-native-nitro-modules RUNTIME — nitrogen is never invoked.
//
// Registration happens automatically at library-load time via a static
// initializer (`register_on_load` below). This runs on every platform the
// moment the shared library is mapped in:
//   * Android: `System.loadLibrary("<module>")`
//   * iOS:     dynamic link / load
//   * Desktop: `dlopen`
// so the HybridObjectRegistry is populated before any JS calls
// `NitroModules.createHybridObject<T>()`.
//
// `extern "C" void registerNatives(jsi::Runtime&)` is kept for the desktop
// Nitro test runner (`cpp/test-harness/test-runner-nitro.cpp`), which
// `dlsym`s and calls it after `dlopen`. Both the static initializer and an
// explicit `registerNatives()` call funnel through a `std::once_flag`, so
// registration is idempotent and never happens twice.

#include <NitroModules/Dispatcher.hpp>
#include <NitroModules/HybridObjectRegistry.hpp>
#include <nitro-uniffi/js_dispatcher.hpp>
#include <jsi/jsi.h>
#include <memory>
#include <mutex>

{%- for entry in hybrid_objects %}
// Pulls the impl in so the symbol is available at link time.
#include "{{ entry.cxx_class }}.hpp"
{%- endfor %}

namespace {
// Guards `register_natives_impl` so the constructors are inserted into the
// process-global `HybridObjectRegistry` exactly once, regardless of whether
// the static initializer, the test runner, or both reach this code.
std::once_flag g_register_once;

void register_natives_impl() {
  using namespace margelo::nitro;
{%- for entry in hybrid_objects %}
  HybridObjectRegistry::registerHybridObjectConstructor(
      "{{ entry.name }}",
      []() -> std::shared_ptr<HybridObject> {
        return std::make_shared<::margelo::nitro::{{ entry.cxx_namespace }}::{{ entry.cxx_class }}>();
      });
{%- endfor %}
}

// Static initializer: its constructor runs at library-load time on all
// platforms (Android `System.loadLibrary`, iOS load, desktop `dlopen`),
// before any user code, so HybridObjects are ready immediately.
struct RegisterOnLoad {
  RegisterOnLoad() {
    std::call_once(g_register_once, register_natives_impl);
  }
};
RegisterOnLoad register_on_load;
} // namespace

extern "C" void registerNatives(facebook::jsi::Runtime& runtime) {
  // Nitro's HybridObjectRegistry is process-global, and the host runner
  // installs the Dispatcher separately via `installNitro` *before* calling
  // this. The `std::once_flag` makes the registration a no-op if the static
  // initializer above has already run (the common mobile case).
  std::call_once(g_register_once, register_natives_impl);

  // Cache the JS-thread Dispatcher for the runtime-less RustFuture continuation
  // to defer re-polls onto (see `nitro-uniffi/future.hpp`). This is the one
  // place we're handed a runtime after the Dispatcher is installed. Guarded so
  // a runtime without a Dispatcher (older host) is a non-fatal no-op.
  try {
    ::ubrn::nitro::set_js_dispatcher(
        ::margelo::nitro::Dispatcher::getRuntimeGlobalDispatcher(runtime));
  } catch (...) {
    // No Dispatcher installed for this runtime — the continuation falls back to
    // an inline re-poll (correct for single-poll futures; the deferral only
    // matters for genuinely-suspending ones).
  }
}
